Doxygen: DTrackSDK Class Reference
DTrackSDK Class Reference
DTrack SDK main class.
#include <DTrackSDK.hpp>
Public Types
enum RemoteSystemType {
SYS_DTRACK_UNKNOWN = 0, SYS_DTRACK, SYS_DTRACK_2, SYS_DTRACK_UNKNOWN = 0,
SYS_DTRACK, SYS_DTRACK_2, SYS_DTRACK_UNKNOWN = 0, SYS_DTRACK,
SYS_DTRACK_2
}
Compatibility modes for older SDKs.
enum Errors {
ERR_NONE = 0, ERR_TIMEOUT, ERR_NET, ERR_PARSE,
ERR_NONE = 0, ERR_TIMEOUT, ERR_NET, ERR_PARSE,
ERR_NONE = 0, ERR_TIMEOUT, ERR_NET, ERR_PARSE
}
Error codes.
enum RemoteSystemType {
SYS_DTRACK_UNKNOWN = 0, SYS_DTRACK, SYS_DTRACK_2, SYS_DTRACK_UNKNOWN = 0,
SYS_DTRACK, SYS_DTRACK_2, SYS_DTRACK_UNKNOWN = 0, SYS_DTRACK,
SYS_DTRACK_2
}
Compatibility modes for older SDKs.
enum Errors {
ERR_NONE = 0, ERR_TIMEOUT, ERR_NET, ERR_PARSE,
ERR_NONE = 0, ERR_TIMEOUT, ERR_NET, ERR_PARSE,
ERR_NONE = 0, ERR_TIMEOUT, ERR_NET, ERR_PARSE
}
Error codes.
enum RemoteSystemType {
SYS_DTRACK_UNKNOWN = 0, SYS_DTRACK, SYS_DTRACK_2, SYS_DTRACK_UNKNOWN = 0,
SYS_DTRACK, SYS_DTRACK_2, SYS_DTRACK_UNKNOWN = 0, SYS_DTRACK,
SYS_DTRACK_2
}
Compatibility modes for older SDKs.
enum Errors {
ERR_NONE = 0, ERR_TIMEOUT, ERR_NET, ERR_PARSE,
ERR_NONE = 0, ERR_TIMEOUT, ERR_NET, ERR_PARSE,
ERR_NONE = 0, ERR_TIMEOUT, ERR_NET, ERR_PARSE
}
Error codes.
Public Member Functions
DTrackSDK (unsigned short data_port)
Constructor.
DTrackSDK (const std::string server_host, unsigned short data_port)
Constructor.
DTrackSDK (const std::string server_host, unsigned short server_port, unsigned short data_port)
Constructor.
DTrackSDK (const std::string server_host, unsigned short server_port, unsigned short data_port, RemoteSystemType remote_type, int data_bufsize=32768, int data_timeout_us=1000000, int srv_timeout_us=10000000)
General constructor.
~DTrackSDK ()
Destructor.
bool receive ()
Receive and process one tracking data packet.
bool startMeasurement ()
Start measurement.
bool stopMeasurement ()
Stop measurement.
unsigned short getDataPort ()
Get data port where tracking data is received.
bool isLocalDataPortValid ()
Is UDP socket open to receive tracking data on local machine? An open socket is needed to receive data, but does not guarantee this.
bool isUDPValid ()
Alias for isLocalDataPortValid().
bool isCommandInterfaceValid ()
Is TCP connection for DTrack2 commands active?
bool isTCPValid ()
Alias for isCommandInterfaceValid().
RemoteSystemType getRemoteSystemType ()
Get current remote system type (e.g.
bool setDataTimeoutUS (int timeout)
Set timeout for receiving tracking data.
bool setControllerTimeoutUS (int timeout)
Set timeout for reply of ARTtrack Controller.
Errors getLastDataError ()
Get last error as error code (data transmission).
Errors getLastServerError ()
Get last error as error code (command transmission).
int getLastDTrackError ()
Get last DTrack error code.
std::string getLastDTrackErrorDescription ()
Get last DTrack error description.
bool sendCommand (const std::string command)
Send DTrack command via UDP.
int sendDTrack2Command (const std::string command, std::string *answer=NULL)
Send DTrack2 command to DTrack and receive answer (TCP command interface).
unsigned int getFrameCounter ()
Get frame counter.
double getTimeStamp ()
Get timestamp.
int getNumBody ()
Get number of calibrated standard bodies (as far as known).
DTrack_Body_Type_d * getBody (int id)
Get standard body data.
int getNumFlyStick ()
Get number of calibrated Flysticks.
DTrack_FlyStick_Type_d * getFlyStick (int id)
Get Flystick data.
int getNumMeaTool ()
Get number of calibrated measurement tools.
DTrack_MeaTool_Type_d * getMeaTool (int id)
Get measurement tool data.
int getNumMeaRef ()
Get number of calibrated measurement references.
DTrack_MeaRef_Type_d * getMeaRef (int id)
Get measurement reference data.
int getNumHand ()
Get number of calibrated Fingertracking hands (as far as known).
DTrack_Hand_Type_d * getHand (int id)
Get Fingertracking hand data.
int getNumHuman ()
Get number of calibrated human models (as far as known).
DTrack_Human_Type * getHuman (int id)
Get human model data.
int getNumMarker ()
Get number of tracked single markers.
DTrack_Marker_Type_d * getMarker (int index)
Get single marker data.
bool setParam (const std::string category, const std::string name, const std::string value)
Set DTrack2 parameter.
bool setParam (const std::string parameter)
Set DTrack2 parameter.
bool getParam (const std::string category, const std::string name, std::string &value)
Get DTrack2 parameter.
bool getParam (const std::string parameter, std::string &value)
Get DTrack2 parameter.
bool getMessage ()
Get DTrack2 message.
std::string getMessageOrigin ()
Get origin of last DTrack2 message.
std::string getMessageStatus ()
Get status of last DTrack2 message.
unsigned int getMessageFrameNr ()
Get frame counter of last DTrack2 message.
unsigned int getMessageErrorId ()
Get error id of last DTrack2 message.
std::string getMessageMsg ()
Get message string of last DTrack2 message.
DTrackSDK (unsigned short data_port)
Constructor.
DTrackSDK (const std::string server_host, unsigned short data_port)
Constructor.
DTrackSDK (const std::string server_host, unsigned short server_port, unsigned short data_port)
Constructor.
DTrackSDK (const std::string server_host, unsigned short server_port, unsigned short data_port, RemoteSystemType remote_type, int data_bufsize=32768, int data_timeout_us=1000000, int srv_timeout_us=10000000)
General constructor.
~DTrackSDK ()
Destructor.
bool receive ()
Receive and process one tracking data packet.
bool startMeasurement ()
Start measurement.
bool stopMeasurement ()
Stop measurement.
unsigned short getDataPort ()
Get data port where tracking data is received.
bool isLocalDataPortValid ()
Is UDP socket open to receive tracking data on local machine? An open socket is needed to receive data, but does not guarantee this.
bool isUDPValid ()
Alias for isLocalDataPortValid().
bool isCommandInterfaceValid ()
Is TCP connection for DTrack2 commands active?
bool isTCPValid ()
Alias for isCommandInterfaceValid().
RemoteSystemType getRemoteSystemType ()
Get current remote system type (e.g.
bool setDataTimeoutUS (int timeout)
Set timeout for receiving tracking data.
bool setControllerTimeoutUS (int timeout)
Set timeout for reply of ARTtrack Controller.
Errors getLastDataError ()
Get last error as error code (data transmission).
Errors getLastServerError ()
Get last error as error code (command transmission).
int getLastDTrackError ()
Get last DTrack error code.
std::string getLastDTrackErrorDescription ()
Get last DTrack error description.
bool sendCommand (const std::string command)
Send DTrack command via UDP.
int sendDTrack2Command (const std::string command, std::string *answer=NULL)
Send DTrack2 command to DTrack and receive answer (TCP command interface).
unsigned int getFrameCounter ()
Get frame counter.
double getTimeStamp ()
Get timestamp.
int getNumBody ()
Get number of calibrated standard bodies (as far as known).
DTrack_Body_Type_d * getBody (int id)
Get standard body data.
int getNumFlyStick ()
Get number of calibrated Flysticks.
DTrack_FlyStick_Type_d * getFlyStick (int id)
Get Flystick data.
int getNumMeaTool ()
Get number of calibrated measurement tools.
DTrack_MeaTool_Type_d * getMeaTool (int id)
Get measurement tool data.
int getNumHand ()
Get number of calibrated Fingertracking hands (as far as known).
DTrack_Hand_Type_d * getHand (int id)
Get Fingertracking hand data.
int getNumHuman ()
Get number of calibrated human models (as far as known).
DTrack_Human_Type * getHuman (int id)
Get human model data.
int getNumMarker ()
Get number of tracked single markers.
DTrack_Marker_Type_d * getMarker (int index)
Get single marker data.
bool setParam (const std::string category, const std::string name, const std::string value)
Set DTrack2 parameter.
bool setParam (const std::string parameter)
Set DTrack2 parameter.
bool getParam (const std::string category, const std::string name, std::string &value)
Get DTrack2 parameter.
bool getParam (const std::string parameter, std::string &value)
Get DTrack2 parameter.
bool getMessage ()
Get DTrack2 message.
std::string getMessageOrigin ()
Get origin of last DTrack2 message.
std::string getMessageStatus ()
Get status of last DTrack2 message.
unsigned int getMessageFrameNr ()
Get frame counter of last DTrack2 message.
unsigned int getMessageErrorId ()
Get error id of last DTrack2 message.
std::string getMessageMsg ()
Get message string of last DTrack2 message.
DTrackSDK (unsigned short data_port)
Constructor.
DTrackSDK (const std::string server_host, unsigned short data_port)
Constructor.
DTrackSDK (const std::string server_host, unsigned short server_port, unsigned short data_port)
Constructor.
DTrackSDK (const std::string server_host, unsigned short server_port, unsigned short data_port, RemoteSystemType remote_type, int data_bufsize=32768, int data_timeout_us=1000000, int srv_timeout_us=10000000)
General constructor.
~DTrackSDK ()
Destructor.
bool receive ()
Receive and process one tracking data packet.
bool startMeasurement ()
Start measurement.
bool stopMeasurement ()
Stop measurement.
unsigned short getDataPort ()
Get data port where tracking data is received.
bool isLocalDataPortValid ()
Is UDP socket open to receive tracking data on local machine? An open socket is needed to receive data, but does not guarantee this.
bool isUDPValid ()
Alias for isLocalDataPortValid().
bool isCommandInterfaceValid ()
Is TCP connection for DTrack2 commands active?
bool isTCPValid ()
Alias for isCommandInterfaceValid().
RemoteSystemType getRemoteSystemType ()
Get current remote system type (e.g.
bool setDataTimeoutUS (int timeout)
Set timeout for receiving tracking data.
bool setControllerTimeoutUS (int timeout)
Set timeout for reply of ARTtrack Controller.
Errors getLastDataError ()
Get last error as error code (data transmission).
Errors getLastServerError ()
Get last error as error code (command transmission).
int getLastDTrackError ()
Get last DTrack error code.
std::string getLastDTrackErrorDescription ()
Get last DTrack error description.
bool sendCommand (const std::string command)
Send DTrack command via UDP.
int sendDTrack2Command (const std::string command, std::string *answer=NULL)
Send DTrack2 command to DTrack and receive answer (TCP command interface).
unsigned int getFrameCounter ()
Get frame counter.
double getTimeStamp ()
Get timestamp.
int getNumBody ()
Get number of calibrated standard bodies (as far as known).
DTrack_Body_Type_d * getBody (int id)
Get standard body data.
int getNumFlyStick ()
Get number of calibrated Flysticks.
DTrack_FlyStick_Type_d * getFlyStick (int id)
Get Flystick data.
int getNumMeaTool ()
Get number of calibrated measurement tools.
DTrack_MeaTool_Type_d * getMeaTool (int id)
Get measurement tool data.
int getNumMeaRef ()
Get number of calibrated measurement references.
DTrack_MeaRef_Type_d * getMeaRef (int id)
Get measurement reference data.
int getNumHand ()
Get number of calibrated Fingertracking hands (as far as known).
DTrack_Hand_Type_d * getHand (int id)
Get Fingertracking hand data.
int getNumHuman ()
Get number of calibrated human models (as far as known).
DTrack_Human_Type * getHuman (int id)
Get human model data.
int getNumMarker ()
Get number of tracked single markers.
DTrack_Marker_Type_d * getMarker (int index)
Get single marker data.
bool setParam (const std::string category, const std::string name, const std::string value)
Set DTrack2 parameter.
bool setParam (const std::string parameter)
Set DTrack2 parameter.
bool getParam (const std::string category, const std::string name, std::string &value)
Get DTrack2 parameter.
bool getParam (const std::string parameter, std::string &value)
Get DTrack2 parameter.
bool getMessage ()
Get DTrack2 message.
std::string getMessageOrigin ()
Get origin of last DTrack2 message.
std::string getMessageStatus ()
Get status of last DTrack2 message.
unsigned int getMessageFrameNr ()
Get frame counter of last DTrack2 message.
unsigned int getMessageErrorId ()
Get error id of last DTrack2 message.
std::string getMessageMsg ()
Get message string of last DTrack2 message.
Detailed Description
DTrack SDK main class.
Definition at line 69 of file DTrackSDK.hpp.
Member Enumeration Documentation
enum DTrackSDK::RemoteSystemType
Compatibility modes for older SDKs.
Enumerator:
SYS_DTRACK_UNKNOWN unknown system
SYS_DTRACK DTrack system.
SYS_DTRACK_2 DTrack2 system.
SYS_DTRACK_UNKNOWN unknown system
SYS_DTRACK DTrack system.
SYS_DTRACK_2 DTrack2 system.
SYS_DTRACK_UNKNOWN unknown system
SYS_DTRACK DTrack system.
SYS_DTRACK_2 DTrack2 system.
Definition at line 74 of file DTrackSDK.hpp.
enum DTrackSDK::Errors
Error codes.
Enumerator:
ERR_NONE no error
ERR_TIMEOUT timeout occured
ERR_NET network error
ERR_PARSE error while parsing command
ERR_NONE no error
ERR_TIMEOUT timeout occured
ERR_NET network error
ERR_PARSE error while parsing command
ERR_NONE no error
ERR_TIMEOUT timeout occured
ERR_NET network error
ERR_PARSE error while parsing command
Definition at line 81 of file DTrackSDK.hpp.
enum DTrackSDK::RemoteSystemType
Compatibility modes for older SDKs.
Enumerator:
SYS_DTRACK_UNKNOWN unknown system
SYS_DTRACK DTrack system.
SYS_DTRACK_2 DTrack2 system.
SYS_DTRACK_UNKNOWN unknown system
SYS_DTRACK DTrack system.
SYS_DTRACK_2 DTrack2 system.
SYS_DTRACK_UNKNOWN unknown system
SYS_DTRACK DTrack system.
SYS_DTRACK_2 DTrack2 system.
Definition at line 74 of file DTrackSDK.hpp.
enum DTrackSDK::Errors
Error codes.
Enumerator:
ERR_NONE no error
ERR_TIMEOUT timeout occured
ERR_NET network error
ERR_PARSE error while parsing command
ERR_NONE no error
ERR_TIMEOUT timeout occured
ERR_NET network error
ERR_PARSE error while parsing command
ERR_NONE no error
ERR_TIMEOUT timeout occured
ERR_NET network error
ERR_PARSE error while parsing command
Definition at line 81 of file DTrackSDK.hpp.
enum DTrackSDK::RemoteSystemType
Compatibility modes for older SDKs.
Enumerator:
SYS_DTRACK_UNKNOWN unknown system
SYS_DTRACK DTrack system.
SYS_DTRACK_2 DTrack2 system.
SYS_DTRACK_UNKNOWN unknown system
SYS_DTRACK DTrack system.
SYS_DTRACK_2 DTrack2 system.
SYS_DTRACK_UNKNOWN unknown system
SYS_DTRACK DTrack system.
SYS_DTRACK_2 DTrack2 system.
Definition at line 74 of file DTrackSDK.hpp.
enum DTrackSDK::Errors
Error codes.
Enumerator:
ERR_NONE no error
ERR_TIMEOUT timeout occured
ERR_NET network error
ERR_PARSE error while parsing command
ERR_NONE no error
ERR_TIMEOUT timeout occured
ERR_NET network error
ERR_PARSE error while parsing command
ERR_NONE no error
ERR_TIMEOUT timeout occured
ERR_NET network error
ERR_PARSE error while parsing command
Definition at line 81 of file DTrackSDK.hpp.
Constructor & Destructor Documentation
DTrackSDK::DTrackSDK (unsigned short data_port)
Constructor.
Use for listening mode.
Parameters:
[in] data_port port number to receive tracking data from DTrack
Definition at line 48 of file DTrackSDK.cpp.
References SYS_DTRACK_UNKNOWN.
DTrackSDK::DTrackSDK (const std::string server_host, unsigned short data_port)
Constructor.
Use for DTrack2.
Parameters:
[in] server_host hostname or IP address of ARTtrack Controller (empty string if not used)
[in] data_port port number to receive tracking data from DTrack
Definition at line 59 of file DTrackSDK.cpp.
References SYS_DTRACK_2.
DTrackSDK::DTrackSDK (const std::string server_host, unsigned short server_port, unsigned short data_port)
Constructor.
Use for DTrack.
This constructor can also be used for DTrack2. In this case server_port must be 50105.
Parameters:
[in] server_host hostname or IP address of ARTtrack Controller (empty string if not used)
[in] server_port port number of DTrack
[in] data_port port number to receive tracking data from DTrack
Definition at line 74 of file DTrackSDK.cpp.
References SYS_DTRACK_UNKNOWN.
DTrackSDK::DTrackSDK (const std::string server_host, unsigned short server_port, unsigned short data_port, RemoteSystemType remote_type, int data_bufsize = 32768, int data_timeout_us = 1000000, int srv_timeout_us = 10000000)
General constructor.
std::vector<DTrack_Monitor2D_Type> act_2d; //!< array with marker data for each camera
Parameters:
[in] server_host hostname or IP address of ARTtrack Controller (empty string if not used)
[in] server_port port number of ARTtrack Controller
[in] data_port port number to receive tracking data from ARTtrack Controller (0 if to be chosen)
[in] remote_type type of system to connect to
[in] data_bufsize size of buffer for UDP packets in bytes; default is 32kb (32768 bytes)
[in] data_timeout_us timeout for receiving tracking data in us; default is 1s (1,000,000 us)
[in] srv_timeout_us timeout for reply of ARTtrack Controller in us; default is 10s (10,000,000 us)
General constructor.
Parameters:
[in] server_host hostname or IP address of ARTtrack Controller (empty string if not used)
[in] server_port port number of ARTtrack Controller
[in] data_port port number to receive tracking data from ARTtrack Controller (0 if to be chosen)
[in] remote_type type of system to connect to
[in] data_bufsize size of buffer for UDP packets in bytes; default is 32kb (32768 bytes)
[in] data_timeout_us timeout for receiving tracking data in us; default is 1s (1,000,000 us)
[in] srv_timeout_us timeout for reply of ARTtrack Controller in us; default is 10s (10,000,000 us)
Definition at line 91 of file DTrackSDK.cpp.
DTrackSDK::~DTrackSDK ()
Destructor.
Definition at line 197 of file DTrackSDK.cpp.
References DTrackSDK_Net::net_exit(), DTrackSDK_Net::tcp_exit(), and DTrackSDK_Net::udp_exit().
DTrackSDK::DTrackSDK (unsigned short data_port)
Constructor.
Use for listening mode.
Parameters:
[in] data_port port number to receive tracking data from DTrack
DTrackSDK::DTrackSDK (const std::string server_host, unsigned short data_port)
Constructor.
Use for DTrack2.
Parameters:
[in] server_host hostname or IP address of ARTtrack Controller (empty string if not used)
[in] data_port port number to receive tracking data from DTrack
DTrackSDK::DTrackSDK (const std::string server_host, unsigned short server_port, unsigned short data_port)
Constructor.
Use for DTrack.
This constructor can also be used for DTrack2. In this case server_port must be 50105.
Parameters:
[in] server_host hostname or IP address of ARTtrack Controller (empty string if not used)
[in] server_port port number of DTrack
[in] data_port port number to receive tracking data from DTrack
DTrackSDK::DTrackSDK (const std::string server_host, unsigned short server_port, unsigned short data_port, RemoteSystemType remote_type, int data_bufsize = 32768, int data_timeout_us = 1000000, int srv_timeout_us = 10000000)
General constructor.
Parameters:
[in] server_host hostname or IP address of ARTtrack Controller (empty string if not used)
[in] server_port port number of ARTtrack Controller
[in] data_port port number to receive tracking data from ARTtrack Controller (0 if to be chosen)
[in] remote_type type of system to connect to
[in] data_bufsize size of buffer for UDP packets in bytes; default is 32kb (32768 bytes)
[in] data_timeout_us timeout for receiving tracking data in us; default is 1s (1,000,000 us)
[in] srv_timeout_us timeout for reply of ARTtrack Controller in us; default is 10s (10,000,000 us)
DTrackSDK::~DTrackSDK ()
Destructor.
DTrackSDK::DTrackSDK (unsigned short data_port)
Constructor.
Use for listening mode.
Parameters:
[in] data_port port number to receive tracking data from DTrack
DTrackSDK::DTrackSDK (const std::string server_host, unsigned short data_port)
Constructor.
Use for DTrack2.
Parameters:
[in] server_host hostname or IP address of ARTtrack Controller (empty string if not used)
[in] data_port port number to receive tracking data from DTrack
DTrackSDK::DTrackSDK (const std::string server_host, unsigned short server_port, unsigned short data_port)
Constructor.
Use for DTrack.
This constructor can also be used for DTrack2. In this case server_port must be 50105.
Parameters:
[in] server_host hostname or IP address of ARTtrack Controller (empty string if not used)
[in] server_port port number of DTrack
[in] data_port port number to receive tracking data from DTrack
DTrackSDK::DTrackSDK (const std::string server_host, unsigned short server_port, unsigned short data_port, RemoteSystemType remote_type, int data_bufsize = 32768, int data_timeout_us = 1000000, int srv_timeout_us = 10000000)
General constructor.
Parameters:
[in] server_host hostname or IP address of ARTtrack Controller (empty string if not used)
[in] server_port port number of ARTtrack Controller
[in] data_port port number to receive tracking data from ARTtrack Controller (0 if to be chosen)
[in] remote_type type of system to connect to
[in] data_bufsize size of buffer for UDP packets in bytes; default is 32kb (32768 bytes)
[in] data_timeout_us timeout for receiving tracking data in us; default is 1s (1,000,000 us)
[in] srv_timeout_us timeout for reply of ARTtrack Controller in us; default is 10s (10,000,000 us)
DTrackSDK::~DTrackSDK ()
Destructor.
Member Function Documentation
bool DTrackSDK::receive ()
Receive and process one tracking data packet.
Updates internal data structures.
Returns:
receive succeeded?
Definition at line 340 of file DTrackSDK.cpp.
References DTRACK_FLYSTICK_MAX_BUTTON, DTRACK_FLYSTICK_MAX_JOYSTICK, DTRACK_HAND_MAX_FINGER, ERR_NET, ERR_NONE, ERR_PARSE, ERR_TIMEOUT, isLocalDataPortValid(), DTrackSDK_Parse::string_get_block(), DTrackSDK_Parse::string_get_d(), DTrackSDK_Parse::string_get_i(), DTrackSDK_Parse::string_get_ui(), DTrackSDK_Parse::string_nextline(), and DTrackSDK_Net::udp_receive().
Referenced by main(), DTracklib::receive(), DTrack2::receive(), and DTrack::receive().
bool DTrackSDK::startMeasurement ()
Start measurement.
Ensure via DTrack frontend that data is sent to the local data port.
Returns:
Is command successful? If measurement is already running the return value is false.
Definition at line 1388 of file DTrackSDK.cpp.
References sendCommand(), sendDTrack2Command(), and SYS_DTRACK.
Referenced by main(), and sendCommand().
bool DTrackSDK::stopMeasurement ()
Stop measurement.
Returns:
Is command successful? If measurement is not running return value is true.
Definition at line 1405 of file DTrackSDK.cpp.
References sendCommand(), sendDTrack2Command(), and SYS_DTRACK.
Referenced by main(), and sendCommand().
unsigned short DTrackSDK::getDataPort ()
Get data port where tracking data is received.
Returns:
Data port.
Definition at line 1322 of file DTrackSDK.cpp.
Referenced by DTrack2::get_data_port(), and main().
bool DTrackSDK::isLocalDataPortValid ()
Is UDP socket open to receive tracking data on local machine? An open socket is needed to receive data, but does not guarantee this.
Especially in case no data is sent to this port.
Replaces valid() in older SDKs.
Returns:
socket open?
Definition at line 316 of file DTrackSDK.cpp.
Referenced by isUDPValid(), main(), receive(), DTrack2::receive(), DTracklib::send(), sendCommand(), DTracklib::valid(), DTrack2::valid(), and DTrack::valid().
bool DTrackSDK::isUDPValid () [inline]
Alias for isLocalDataPortValid().
Due to compatibility to DTrackSDK v2.0.0.
Definition at line 183 of file DTrackSDK.hpp.
References isLocalDataPortValid().
bool DTrackSDK::isCommandInterfaceValid ()
Is TCP connection for DTrack2 commands active?
On DTrack systems this function returns always false.
Returns:
command interface active?
Definition at line 328 of file DTrackSDK.cpp.
Referenced by isTCPValid(), main(), sendDTrack2Command(), and DTrack2::server_noconnection().
bool DTrackSDK::isTCPValid () [inline]
Alias for isCommandInterfaceValid().
Due to compatibility to DTrackSDK v2.0.0.
Definition at line 197 of file DTrackSDK.hpp.
References isCommandInterfaceValid().
DTrackSDK::RemoteSystemType DTrackSDK::getRemoteSystemType ()
Get current remote system type (e.g.
DTrack, DTrack2).
Returns:
type of remote system
Definition at line 246 of file DTrackSDK.cpp.
bool DTrackSDK::setDataTimeoutUS (int timeout)
Set timeout for receiving tracking data.
Parameters:
[in] timeout timeout for receiving tracking data in us; default is 1s (1,000,000 us)
Returns:
Success? (i.e. valid timeout)
Definition at line 219 of file DTrackSDK.cpp.
bool DTrackSDK::setControllerTimeoutUS (int timeout)
Set timeout for reply of ARTtrack Controller.
Parameters:
[in] timeout timeout for reply of ARTtrack Controller in us; default is 1s (1,000,000 us)
Returns:
Success? (i.e. valid timeout)
Definition at line 233 of file DTrackSDK.cpp.
DTrackSDK::Errors DTrackSDK::getLastDataError ()
Get last error as error code (data transmission).
Returns:
error code (success = 0)
Definition at line 256 of file DTrackSDK.cpp.
Referenced by data_error_to_console(), DTrack2::data_neterror(), DTrack2::data_parseerror(), DTrack2::data_timeout(), error_to_console(), DTracklib::parseerror(), DTrack::parseerror(), DTracklib::timeout(), DTrack::timeout(), DTracklib::udperror(), and DTrack::udperror().
DTrackSDK::Errors DTrackSDK::getLastServerError ()
Get last error as error code (command transmission).
Returns:
error code (success = 0)
Definition at line 267 of file DTrackSDK.cpp.
Referenced by DTrack2::server_neterror(), DTrack2::server_parseerror(), and DTrack2::server_timeout().
int DTrackSDK::getLastDTrackError ()
Get last DTrack error code.
Returns:
Error code.
Definition at line 291 of file DTrackSDK.cpp.
Referenced by DTrack2::get_lasterror().
std::string DTrackSDK::getLastDTrackErrorDescription ()
Get last DTrack error description.
Returns:
Error description.
Definition at line 302 of file DTrackSDK.cpp.
Referenced by DTrack2::get_lasterror().
bool DTrackSDK::sendCommand (const std::string command)
Send DTrack command via UDP.
Answer is not received and therefore not processed.
Parameters:
[in] command command string
Returns:
sending command succeeded? if not, a DTrack error is available
Definition at line 1042 of file DTrackSDK.cpp.
References ERR_NET, ERR_NONE, isLocalDataPortValid(), startMeasurement(), stopMeasurement(), SYS_DTRACK_2, and DTrackSDK_Net::udp_send().
Referenced by DTrack::cmd_cameras(), DTrack::cmd_sending_data(), DTrack::cmd_sending_fixed_data(), DTrack::cmd_tracking(), DTracklib::send(), startMeasurement(), and stopMeasurement().
int DTrackSDK::sendDTrack2Command (const std::string command, std::string * answer = NULL)
Send DTrack2 command to DTrack and receive answer (TCP command interface).
Answers like "dtrack2 ok" and "dtrack2 err .." are processed. Both cases are reflected in the return value. getLastDTrackError() and getLastDTrackErrorDescription() will return more information.
Parameters:
[in] command DTrack2 command string
[out] answer buffer for answer; NULL if specific answer is not needed
Returns:
0 specific answer, needs to be parsed
1 answer is "dtrack2 ok"
2 answer is "dtrack2 err ..". Refer to getLastDTrackError() and getLastDTrackErrorDescription().
<0 if error occured (-1 receive timeout, -2 wrong system type, -3 command too long, -9 broken tcp connection, -10 tcp connection invalid, -11 send command failed)
Definition at line 1097 of file DTrackSDK.cpp.
References DTRACK_PROT_MAXLEN, ERR_NET, ERR_NONE, ERR_PARSE, ERR_TIMEOUT, isCommandInterfaceValid(), DTrackSDK_Parse::string_get_i(), DTrackSDK_Parse::string_get_quoted_text(), SYS_DTRACK_2, DTrackSDK_Net::tcp_exit(), DTrackSDK_Net::tcp_receive(), and DTrackSDK_Net::tcp_send().
Referenced by getMessage(), getParam(), DTrack2::send_command(), setParam(), startMeasurement(), and stopMeasurement().
unsigned int DTrackSDK::getFrameCounter ()
Get frame counter.
Refers to last received frame.
Returns:
frame counter
Definition at line 1017 of file DTrackSDK.cpp.
Referenced by DTrack2::get_framecounter(), DTrack::get_framecounter(), DTracklib::get_framenr(), and output_to_console().
double DTrackSDK::getTimeStamp ()
Get timestamp.
Refers to last received frame.
Returns:
timestamp (-1 if information not available)
Definition at line 1029 of file DTrackSDK.cpp.
Referenced by DTracklib::get_timestamp(), DTrack2::get_timestamp(), DTrack::get_timestamp(), and output_to_console().
int DTrackSDK::getNumBody ()
Get number of calibrated standard bodies (as far as known).
Refers to last received frame.
Returns:
number of calibrated standard bodies
Definition at line 828 of file DTrackSDK.cpp.
Referenced by output_to_console(), DTracklib::receive(), DTrack2::receive(), and DTrack::receive().
DTrack_Body_Type_d * DTrackSDK::getBody (int id)
Get standard body data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max standard body id - 1)
Returns:
id-th standard body data
Definition at line 841 of file DTrackSDK.cpp.
Referenced by output_to_console(), DTracklib::receive(), DTrack2::receive(), and DTrack::receive().
int DTrackSDK::getNumFlyStick ()
Get number of calibrated Flysticks.
Refers to last received frame.
Returns:
Number of calibrated Flysticks.
Refers to last received frame.
Returns:
number of calibrated Flysticks
Definition at line 855 of file DTrackSDK.cpp.
Referenced by output_to_console(), DTracklib::receive(), DTrack2::receive(), and DTrack::receive().
DTrack_FlyStick_Type_d * DTrackSDK::getFlyStick (int id)
Get Flystick data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max flystick id - 1)
Returns:
id-th Flystick data.
Definition at line 868 of file DTrackSDK.cpp.
Referenced by output_to_console(), DTracklib::receive(), DTrack2::receive(), and DTrack::receive().
int DTrackSDK::getNumMeaTool ()
Get number of calibrated measurement tools.
Refers to last received frame.
Returns:
Number of calibrated measurement tools.
Refers to last received frame.
Returns:
number of calibrated measurement tools
Definition at line 882 of file DTrackSDK.cpp.
Referenced by output_to_console(), DTracklib::receive(), DTrack2::receive(), and DTrack::receive().
DTrack_MeaTool_Type_d * DTrackSDK::getMeaTool (int id)
Get measurement tool data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max tool id - 1)
Returns:
id-th measurement tool data.
Definition at line 895 of file DTrackSDK.cpp.
Referenced by output_to_console(), DTracklib::receive(), DTrack2::receive(), and DTrack::receive().
int DTrackSDK::getNumMeaRef ()
Get number of calibrated measurement references.
Refers to last received frame.
Returns:
Number of calibrated measurement references.
Refers to last received frame.
Returns:
number of calibrated measurement references
Definition at line 909 of file DTrackSDK.cpp.
Referenced by output_to_console().
DTrack_MeaRef_Type_d * DTrackSDK::getMeaRef (int id)
Get measurement reference data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max tool id - 1)
Returns:
id-th measurement reference data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max measurement reference id - 1)
Returns:
id-th measurement reference data.
Definition at line 922 of file DTrackSDK.cpp.
Referenced by output_to_console().
int DTrackSDK::getNumHand ()
Get number of calibrated Fingertracking hands (as far as known).
Refers to last received frame.
Returns:
Number of calibrated Fingertracking hands (as far as known).
Refers to last received frame.
Returns:
number of calibrated fingertracking hands
Definition at line 936 of file DTrackSDK.cpp.
Referenced by output_to_console(), DTracklib::receive(), DTrack2::receive(), and DTrack::receive().
DTrack_Hand_Type_d * DTrackSDK::getHand (int id)
Get Fingertracking hand data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max hand id - 1)
Returns:
id-th Fingertracking hand data
Definition at line 949 of file DTrackSDK.cpp.
Referenced by output_to_console(), DTracklib::receive(), DTrack2::receive(), and DTrack::receive().
int DTrackSDK::getNumHuman ()
Get number of calibrated human models (as far as known).
Get human data.
Refers to last received frame.
Returns:
number of calibrated human models
Refers to last received frame. Currently not tracked human models get a num_joints 0
Returns:
id-th human model data
Definition at line 963 of file DTrackSDK.cpp.
Referenced by output_to_console().
DTrack_Human_Type * DTrackSDK::getHuman (int id)
Get human model data.
Get human data.
Refers to last received frame. Currently not tracked human models get a num_joints 0
Parameters:
[in] id id, range 0 .. (max standard body id - 1)
Returns:
id-th human model data
Definition at line 976 of file DTrackSDK.cpp.
Referenced by output_to_console().
int DTrackSDK::getNumMarker ()
Get number of tracked single markers.
Refers to last received frame.
Returns:
number of tracked single markers
Definition at line 990 of file DTrackSDK.cpp.
Referenced by output_to_console(), DTracklib::receive(), DTrack2::receive(), and DTrack::receive().
DTrack_Marker_Type_d * DTrackSDK::getMarker (int index)
Get single marker data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] index index, range 0 .. (max marker id - 1)
Returns:
i-th single marker data
Definition at line 1003 of file DTrackSDK.cpp.
Referenced by output_to_console(), DTracklib::receive(), DTrack2::receive(), and DTrack::receive().
bool DTrackSDK::setParam (const std::string category, const std::string name, const std::string value)
Set DTrack2 parameter.
Parameters:
[in] category parameter category
[in] name parameter name
[in] value parameter value
Returns:
success? (if not, a DTrack error message is available)
Definition at line 1192 of file DTrackSDK.cpp.
bool DTrackSDK::setParam (const std::string parameter)
Set DTrack2 parameter.
Parameters:
[in] parameter complete parameter string without starting "dtrack set "
Returns:
success? (if not, a DTrack error message is available)
Definition at line 1204 of file DTrackSDK.cpp.
References sendDTrack2Command().
bool DTrackSDK::getParam (const std::string category, const std::string name, std::string & value)
Get DTrack2 parameter.
Parameters:
[in] category parameter category
[in] name parameter name
[out] value parameter value
Returns:
success? (if not, a DTrack error message is available)
Definition at line 1219 of file DTrackSDK.cpp.
Referenced by DTrack2::get_parameter().
bool DTrackSDK::getParam (const std::string parameter, std::string & value)
Get DTrack2 parameter.
Parameters:
[in] parameter complete parameter string without starting "dtrack get "
[out] value parameter value
Returns:
success? (if not, a DTrack error message is available)
Definition at line 1232 of file DTrackSDK.cpp.
References ERR_PARSE, sendDTrack2Command(), DTrackSDK_Parse::string_cmp_parameter(), and SYS_DTRACK_2.
bool DTrackSDK::getMessage ()
Get DTrack2 message.
Updates internal message structures
Returns:
message available?
Definition at line 1269 of file DTrackSDK.cpp.
References sendDTrack2Command(), DTrackSDK_Parse::string_get_quoted_text(), DTrackSDK_Parse::string_get_ui(), DTrackSDK_Parse::string_get_word(), and SYS_DTRACK_2.
Referenced by DTrack2::get_message(), and messages_to_console().
std::string DTrackSDK::getMessageOrigin ()
Get origin of last DTrack2 message.
Returns:
origin
Definition at line 1333 of file DTrackSDK.cpp.
Referenced by DTrack2::get_message_origin().
std::string DTrackSDK::getMessageStatus ()
Get status of last DTrack2 message.
Returns:
status
Definition at line 1343 of file DTrackSDK.cpp.
Referenced by DTrack2::get_message_status(), and messages_to_console().
unsigned int DTrackSDK::getMessageFrameNr ()
Get frame counter of last DTrack2 message.
Returns:
frame counter
Definition at line 1354 of file DTrackSDK.cpp.
Referenced by DTrack2::get_message_framenr().
unsigned int DTrackSDK::getMessageErrorId ()
Get error id of last DTrack2 message.
Returns:
error id
Definition at line 1365 of file DTrackSDK.cpp.
Referenced by DTrack2::get_message_errorid().
std::string DTrackSDK::getMessageMsg ()
Get message string of last DTrack2 message.
Returns:
mesage string
Definition at line 1376 of file DTrackSDK.cpp.
Referenced by DTrack2::get_message_msg(), and messages_to_console().
bool DTrackSDK::receive ()
Receive and process one tracking data packet.
Updates internal data structures.
Returns:
receive succeeded?
bool DTrackSDK::startMeasurement ()
Start measurement.
Ensure via DTrack frontend that data is sent to the local data port.
Returns:
Is command successful? If measurement is already running the return value is false.
bool DTrackSDK::stopMeasurement ()
Stop measurement.
Returns:
Is command successful? If measurement is not running return value is true.
unsigned short DTrackSDK::getDataPort ()
Get data port where tracking data is received.
Returns:
Data port.
bool DTrackSDK::isLocalDataPortValid ()
Is UDP socket open to receive tracking data on local machine? An open socket is needed to receive data, but does not guarantee this.
Especially in case no data is sent to this port.
Replaces valid() in older SDKs.
Returns:
socket open?
bool DTrackSDK::isUDPValid () [inline]
Alias for isLocalDataPortValid().
Due to compatibility to DTrackSDK v2.0.0.
Definition at line 183 of file DTrackSDK.hpp.
References isLocalDataPortValid().
bool DTrackSDK::isCommandInterfaceValid ()
Is TCP connection for DTrack2 commands active?
On DTrack systems this function returns always false.
Returns:
command interface active?
bool DTrackSDK::isTCPValid () [inline]
Alias for isCommandInterfaceValid().
Due to compatibility to DTrackSDK v2.0.0.
Definition at line 197 of file DTrackSDK.hpp.
References isCommandInterfaceValid().
RemoteSystemType DTrackSDK::getRemoteSystemType ()
Get current remote system type (e.g.
DTrack, DTrack2).
Returns:
type of remote system
bool DTrackSDK::setDataTimeoutUS (int timeout)
Set timeout for receiving tracking data.
Parameters:
[in] timeout timeout for receiving tracking data in us; default is 1s (1,000,000 us)
Returns:
Success? (i.e. valid timeout)
bool DTrackSDK::setControllerTimeoutUS (int timeout)
Set timeout for reply of ARTtrack Controller.
Parameters:
[in] timeout timeout for reply of ARTtrack Controller in us; default is 1s (1,000,000 us)
Returns:
Success? (i.e. valid timeout)
Errors DTrackSDK::getLastDataError ()
Get last error as error code (data transmission).
Returns:
error code (success = 0)
Errors DTrackSDK::getLastServerError ()
Get last error as error code (command transmission).
Returns:
error code (success = 0)
int DTrackSDK::getLastDTrackError ()
Get last DTrack error code.
Returns:
Error code.
std::string DTrackSDK::getLastDTrackErrorDescription ()
Get last DTrack error description.
Returns:
Error description.
bool DTrackSDK::sendCommand (const std::string command)
Send DTrack command via UDP.
Answer is not received and therefore not processed.
Parameters:
[in] command command string
Returns:
sending command succeeded? if not, a DTrack error is available
int DTrackSDK::sendDTrack2Command (const std::string command, std::string * answer = NULL)
Send DTrack2 command to DTrack and receive answer (TCP command interface).
Answers like "dtrack2 ok" and "dtrack2 err .." are processed. Both cases are reflected in the return value. getLastDTrackError() and getLastDTrackErrorDescription() will return more information.
Parameters:
[in] command DTrack2 command string
[out] answer buffer for answer; NULL if specific answer is not needed
Returns:
0 specific answer, needs to be parsed
1 answer is "dtrack2 ok"
2 answer is "dtrack2 err ..". Refer to getLastDTrackError() and getLastDTrackErrorDescription().
<0 if error occured (-1 receive timeout, -2 wrong system type, -3 command too long, -9 broken tcp connection, -10 tcp connection invalid, -11 send command failed)
unsigned int DTrackSDK::getFrameCounter ()
Get frame counter.
Refers to last received frame.
Returns:
frame counter
double DTrackSDK::getTimeStamp ()
Get timestamp.
Refers to last received frame.
Returns:
timestamp (-1 if information not available)
int DTrackSDK::getNumBody ()
Get number of calibrated standard bodies (as far as known).
Refers to last received frame.
Returns:
number of calibrated standard bodies
DTrack_Body_Type_d* DTrackSDK::getBody (int id)
Get standard body data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max standard body id - 1)
Returns:
id-th standard body data
int DTrackSDK::getNumFlyStick ()
Get number of calibrated Flysticks.
Refers to last received frame.
Returns:
Number of calibrated Flysticks.
DTrack_FlyStick_Type_d* DTrackSDK::getFlyStick (int id)
Get Flystick data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max flystick id - 1)
Returns:
id-th Flystick data.
int DTrackSDK::getNumMeaTool ()
Get number of calibrated measurement tools.
Refers to last received frame.
Returns:
Number of calibrated measurement tools.
DTrack_MeaTool_Type_d* DTrackSDK::getMeaTool (int id)
Get measurement tool data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max tool id - 1)
Returns:
id-th measurement tool data.
int DTrackSDK::getNumHand ()
Get number of calibrated Fingertracking hands (as far as known).
Refers to last received frame.
Returns:
Number of calibrated Fingertracking hands (as far as known).
DTrack_Hand_Type_d* DTrackSDK::getHand (int id)
Get Fingertracking hand data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max hand id - 1)
Returns:
id-th Fingertracking hand data
int DTrackSDK::getNumHuman ()
Get number of calibrated human models (as far as known).
Refers to last received frame.
Returns:
number of calibrated human models
DTrack_Human_Type* DTrackSDK::getHuman (int id)
Get human model data.
Refers to last received frame. Currently not tracked human models get a num_joints 0
Parameters:
[in] id id, range 0 .. (max standard body id - 1)
Returns:
id-th human model data
int DTrackSDK::getNumMarker ()
Get number of tracked single markers.
Refers to last received frame.
Returns:
number of tracked single markers
DTrack_Marker_Type_d* DTrackSDK::getMarker (int index)
Get single marker data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] index index, range 0 .. (max marker id - 1)
Returns:
i-th single marker data
bool DTrackSDK::setParam (const std::string category, const std::string name, const std::string value)
Set DTrack2 parameter.
Parameters:
[in] category parameter category
[in] name parameter name
[in] value parameter value
Returns:
success? (if not, a DTrack error message is available)
bool DTrackSDK::setParam (const std::string parameter)
Set DTrack2 parameter.
Parameters:
[in] parameter complete parameter string without starting "dtrack set "
Returns:
success? (if not, a DTrack error message is available)
bool DTrackSDK::getParam (const std::string category, const std::string name, std::string & value)
Get DTrack2 parameter.
Parameters:
[in] category parameter category
[in] name parameter name
[out] value parameter value
Returns:
success? (if not, a DTrack error message is available)
bool DTrackSDK::getParam (const std::string parameter, std::string & value)
Get DTrack2 parameter.
Parameters:
[in] parameter complete parameter string without starting "dtrack get "
[out] value parameter value
Returns:
success? (if not, a DTrack error message is available)
bool DTrackSDK::getMessage ()
Get DTrack2 message.
Updates internal message structures
Returns:
message available?
std::string DTrackSDK::getMessageOrigin ()
Get origin of last DTrack2 message.
Returns:
origin
std::string DTrackSDK::getMessageStatus ()
Get status of last DTrack2 message.
Returns:
status
unsigned int DTrackSDK::getMessageFrameNr ()
Get frame counter of last DTrack2 message.
Returns:
frame counter
unsigned int DTrackSDK::getMessageErrorId ()
Get error id of last DTrack2 message.
Returns:
error id
std::string DTrackSDK::getMessageMsg ()
Get message string of last DTrack2 message.
Returns:
mesage string
bool DTrackSDK::receive ()
Receive and process one tracking data packet.
Updates internal data structures.
Returns:
receive succeeded?
bool DTrackSDK::startMeasurement ()
Start measurement.
Ensure via DTrack frontend that data is sent to the local data port.
Returns:
Is command successful? If measurement is already running the return value is false.
bool DTrackSDK::stopMeasurement ()
Stop measurement.
Returns:
Is command successful? If measurement is not running return value is true.
unsigned short DTrackSDK::getDataPort ()
Get data port where tracking data is received.
Returns:
Data port.
bool DTrackSDK::isLocalDataPortValid ()
Is UDP socket open to receive tracking data on local machine? An open socket is needed to receive data, but does not guarantee this.
Especially in case no data is sent to this port.
Replaces valid() in older SDKs.
Returns:
socket open?
bool DTrackSDK::isUDPValid () [inline]
Alias for isLocalDataPortValid().
Due to compatibility to DTrackSDK v2.0.0.
Definition at line 183 of file DTrackSDK.hpp.
References isLocalDataPortValid().
bool DTrackSDK::isCommandInterfaceValid ()
Is TCP connection for DTrack2 commands active?
On DTrack systems this function returns always false.
Returns:
command interface active?
bool DTrackSDK::isTCPValid () [inline]
Alias for isCommandInterfaceValid().
Due to compatibility to DTrackSDK v2.0.0.
Definition at line 197 of file DTrackSDK.hpp.
References isCommandInterfaceValid().
RemoteSystemType DTrackSDK::getRemoteSystemType ()
Get current remote system type (e.g.
DTrack, DTrack2).
Returns:
type of remote system
bool DTrackSDK::setDataTimeoutUS (int timeout)
Set timeout for receiving tracking data.
Parameters:
[in] timeout timeout for receiving tracking data in us; default is 1s (1,000,000 us)
Returns:
Success? (i.e. valid timeout)
bool DTrackSDK::setControllerTimeoutUS (int timeout)
Set timeout for reply of ARTtrack Controller.
Parameters:
[in] timeout timeout for reply of ARTtrack Controller in us; default is 1s (1,000,000 us)
Returns:
Success? (i.e. valid timeout)
Errors DTrackSDK::getLastDataError ()
Get last error as error code (data transmission).
Returns:
error code (success = 0)
Errors DTrackSDK::getLastServerError ()
Get last error as error code (command transmission).
Returns:
error code (success = 0)
int DTrackSDK::getLastDTrackError ()
Get last DTrack error code.
Returns:
Error code.
std::string DTrackSDK::getLastDTrackErrorDescription ()
Get last DTrack error description.
Returns:
Error description.
bool DTrackSDK::sendCommand (const std::string command)
Send DTrack command via UDP.
Answer is not received and therefore not processed.
Parameters:
[in] command command string
Returns:
sending command succeeded? if not, a DTrack error is available
int DTrackSDK::sendDTrack2Command (const std::string command, std::string * answer = NULL)
Send DTrack2 command to DTrack and receive answer (TCP command interface).
Answers like "dtrack2 ok" and "dtrack2 err .." are processed. Both cases are reflected in the return value. getLastDTrackError() and getLastDTrackErrorDescription() will return more information.
Parameters:
[in] command DTrack2 command string
[out] answer buffer for answer; NULL if specific answer is not needed
Returns:
0 specific answer, needs to be parsed
1 answer is "dtrack2 ok"
2 answer is "dtrack2 err ..". Refer to getLastDTrackError() and getLastDTrackErrorDescription().
<0 if error occured (-1 receive timeout, -2 wrong system type, -3 command too long, -9 broken tcp connection, -10 tcp connection invalid, -11 send command failed)
unsigned int DTrackSDK::getFrameCounter ()
Get frame counter.
Refers to last received frame.
Returns:
frame counter
double DTrackSDK::getTimeStamp ()
Get timestamp.
Refers to last received frame.
Returns:
timestamp (-1 if information not available)
int DTrackSDK::getNumBody ()
Get number of calibrated standard bodies (as far as known).
Refers to last received frame.
Returns:
number of calibrated standard bodies
DTrack_Body_Type_d* DTrackSDK::getBody (int id)
Get standard body data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max standard body id - 1)
Returns:
id-th standard body data
int DTrackSDK::getNumFlyStick ()
Get number of calibrated Flysticks.
Refers to last received frame.
Returns:
Number of calibrated Flysticks.
DTrack_FlyStick_Type_d* DTrackSDK::getFlyStick (int id)
Get Flystick data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max flystick id - 1)
Returns:
id-th Flystick data.
int DTrackSDK::getNumMeaTool ()
Get number of calibrated measurement tools.
Refers to last received frame.
Returns:
Number of calibrated measurement tools.
DTrack_MeaTool_Type_d* DTrackSDK::getMeaTool (int id)
Get measurement tool data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max tool id - 1)
Returns:
id-th measurement tool data.
int DTrackSDK::getNumMeaRef ()
Get number of calibrated measurement references.
Refers to last received frame.
Returns:
Number of calibrated measurement references.
DTrack_MeaRef_Type_d* DTrackSDK::getMeaRef (int id)
Get measurement reference data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max tool id - 1)
Returns:
id-th measurement reference data.
int DTrackSDK::getNumHand ()
Get number of calibrated Fingertracking hands (as far as known).
Refers to last received frame.
Returns:
Number of calibrated Fingertracking hands (as far as known).
DTrack_Hand_Type_d* DTrackSDK::getHand (int id)
Get Fingertracking hand data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] id id, range 0 .. (max hand id - 1)
Returns:
id-th Fingertracking hand data
int DTrackSDK::getNumHuman ()
Get number of calibrated human models (as far as known).
Refers to last received frame.
Returns:
number of calibrated human models
DTrack_Human_Type* DTrackSDK::getHuman (int id)
Get human model data.
Refers to last received frame. Currently not tracked human models get a num_joints 0
Parameters:
[in] id id, range 0 .. (max standard body id - 1)
Returns:
id-th human model data
int DTrackSDK::getNumMarker ()
Get number of tracked single markers.
Refers to last received frame.
Returns:
number of tracked single markers
DTrack_Marker_Type_d* DTrackSDK::getMarker (int index)
Get single marker data.
Refers to last received frame. Currently not tracked bodies get a quality of -1.
Parameters:
[in] index index, range 0 .. (max marker id - 1)
Returns:
i-th single marker data
bool DTrackSDK::setParam (const std::string category, const std::string name, const std::string value)
Set DTrack2 parameter.
Parameters:
[in] category parameter category
[in] name parameter name
[in] value parameter value
Returns:
success? (if not, a DTrack error message is available)
bool DTrackSDK::setParam (const std::string parameter)
Set DTrack2 parameter.
Parameters:
[in] parameter complete parameter string without starting "dtrack set "
Returns:
success? (if not, a DTrack error message is available)
bool DTrackSDK::getParam (const std::string category, const std::string name, std::string & value)
Get DTrack2 parameter.
Parameters:
[in] category parameter category
[in] name parameter name
[out] value parameter value
Returns:
success? (if not, a DTrack error message is available)
bool DTrackSDK::getParam (const std::string parameter, std::string & value)
Get DTrack2 parameter.
Parameters:
[in] parameter complete parameter string without starting "dtrack get "
[out] value parameter value
Returns:
success? (if not, a DTrack error message is available)
bool DTrackSDK::getMessage ()
Get DTrack2 message.
Updates internal message structures
Returns:
message available?
std::string DTrackSDK::getMessageOrigin ()
Get origin of last DTrack2 message.
Returns:
origin
std::string DTrackSDK::getMessageStatus ()
Get status of last DTrack2 message.
Returns:
status
unsigned int DTrackSDK::getMessageFrameNr ()
Get frame counter of last DTrack2 message.
Returns:
frame counter
unsigned int DTrackSDK::getMessageErrorId ()
Get error id of last DTrack2 message.
Returns:
error id
std::string DTrackSDK::getMessageMsg ()
Get message string of last DTrack2 message.
Returns:
mesage string
The documentation for this class was generated from the following files:
DTrackSDK.hpp
ship_it/DTrackSDK_v2.1.0/DTrackSDK.hpp
ship_it/DTrackSDK_v2.2.0/DTrackSDK.hpp
DTrackSDK.cpp
ship_it/DTrackSDK_v2.1.0/DTrackSDK.cpp
ship_it/DTrackSDK_v2.2.0/DTrackSDK.cpp