Doxygen: DTrack2 Class Reference
DTrack2 Class Reference
Wrapper class for DTrack 2 SDK.
#include <DTrack2.hpp>
Public Member Functions
DTrack2 (const std::string &server_host="", unsigned short server_port=50105, unsigned short data_port=0, int data_bufsize=20000, int data_timeout_us=1000000, int server_timeout_us=10000000)
Constructor.
~DTrack2 ()
Destructor.
bool valid ()
Check if initialization was successfull.
unsigned short get_data_port ()
Get used UDP port number.
bool data_timeout ()
Check last data receive error (timeout).
bool data_neterror ()
Check last data receive error (net error).
bool data_parseerror ()
Check last data receive error (parser).
bool server_noconnection ()
Check if connection to DTrack2 server is completely lost.
bool server_timeout ()
Check last command receive/send error (timeout).
bool server_neterror ()
Check last command receive/send error (network).
bool server_parseerror ()
Check last command receive/send error (parsing).
bool receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
unsigned int get_framecounter ()
Get frame counter.
double get_timestamp ()
Get timestamp.
int get_num_body ()
Get number of standard bodies.
dtrack2_body_type get_body (int id)
Get 6d data.
int get_num_flystick ()
Get number of flysticks.
dtrack2_flystick_type get_flystick (int id)
Get 6df data.
int get_num_meatool ()
Get number of measurement tools.
dtrack2_meatool_type get_meatool (int id)
Get 6dmt data.
int get_num_hand ()
Get number of fingertracking hands.
dtrack2_hand_type get_hand (int id)
Get gl data.
int get_num_marker ()
Get number of single markers.
dtrack2_marker_type get_marker (int index)
Get 3d data.
bool set_parameter (const std::string category, const std::string name, const std::string value)
Set DTrack2 parameter.
bool set_parameter (const std::string parameter)
Set DTrack2 parameter.
bool get_parameter (const std::string category, const std::string name, std::string &value)
Get DTrack2 parameter.
bool get_parameter (const std::string parameter, std::string &value)
Get DTrack2 parameter.
bool send_command (const std::string command)
Send DTrack2 command.
bool get_lasterror (int &errorcode)
Get last DTrack2 error code.
bool get_lasterror (std::string &errorstring)
Get last DTrack2 error code.
bool get_message ()
Get DTrack2 message.
std::string get_message_origin ()
Get origin of last DTrack2 message.
std::string get_message_status ()
Get status of last DTrack2 message.
unsigned int get_message_framenr ()
Get frame counter of last DTrack2 message.
unsigned int get_message_errorid ()
Get error id of last DTrack2 message.
std::string get_message_msg ()
Get message string of last DTrack2 message.
DTrack2 (const std::string &server_host="", unsigned short server_port=50105, unsigned short data_port=0, int data_bufsize=20000, int data_timeout_us=1000000, int server_timeout_us=10000000)
Constructor.
~DTrack2 ()
Destructor.
bool valid ()
Check if initialization was successfull.
unsigned short get_data_port ()
Get used UDP port number.
bool data_timeout ()
Check last data receive error (timeout).
bool data_neterror ()
Check last data receive error (net error).
bool data_parseerror ()
Check last data receive error (parser).
bool server_noconnection ()
Check if connection to DTrack2 server is completely lost.
bool server_timeout ()
Check last command receive/send error (timeout).
bool server_neterror ()
Check last command receive/send error (network).
bool server_parseerror ()
Check last command receive/send error (parsing).
bool receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
unsigned int get_framecounter ()
Get frame counter.
double get_timestamp ()
Get timestamp.
int get_num_body ()
Get number of standard bodies.
dtrack2_body_type get_body (int id)
Get 6d data.
int get_num_flystick ()
Get number of flysticks.
dtrack2_flystick_type get_flystick (int id)
Get 6df data.
int get_num_meatool ()
Get number of measurement tools.
dtrack2_meatool_type get_meatool (int id)
Get 6dmt data.
int get_num_hand ()
Get number of fingertracking hands.
dtrack2_hand_type get_hand (int id)
Get gl data.
int get_num_marker ()
Get number of single markers.
dtrack2_marker_type get_marker (int index)
Get 3d data.
bool set_parameter (const std::string category, const std::string name, const std::string value)
Set DTrack2 parameter.
bool set_parameter (const std::string parameter)
Set DTrack2 parameter.
bool get_parameter (const std::string category, const std::string name, std::string &value)
Get DTrack2 parameter.
bool get_parameter (const std::string parameter, std::string &value)
Get DTrack2 parameter.
bool send_command (const std::string command)
Send DTrack2 command.
bool get_lasterror (int &errorcode)
Get last DTrack2 error code.
bool get_lasterror (std::string &errorstring)
Get last DTrack2 error code.
bool get_message ()
Get DTrack2 message.
std::string get_message_origin ()
Get origin of last DTrack2 message.
std::string get_message_status ()
Get status of last DTrack2 message.
unsigned int get_message_framenr ()
Get frame counter of last DTrack2 message.
unsigned int get_message_errorid ()
Get error id of last DTrack2 message.
std::string get_message_msg ()
Get message string of last DTrack2 message.
DTrack2 (const std::string &server_host="", unsigned short server_port=50105, unsigned short data_port=0, int data_bufsize=20000, int data_timeout_us=1000000, int server_timeout_us=10000000)
Constructor.
~DTrack2 ()
Destructor.
bool valid ()
Check if initialization was successfull.
unsigned short get_data_port ()
Get used UDP port number.
bool data_timeout ()
Check last data receive error (timeout).
bool data_neterror ()
Check last data receive error (net error).
bool data_parseerror ()
Check last data receive error (parser).
bool server_noconnection ()
Check if connection to DTrack2 server is completely lost.
bool server_timeout ()
Check last command receive/send error (timeout).
bool server_neterror ()
Check last command receive/send error (network).
bool server_parseerror ()
Check last command receive/send error (parsing).
bool receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
unsigned int get_framecounter ()
Get frame counter.
double get_timestamp ()
Get timestamp.
int get_num_body ()
Get number of standard bodies.
dtrack2_body_type get_body (int id)
Get 6d data.
int get_num_flystick ()
Get number of flysticks.
dtrack2_flystick_type get_flystick (int id)
Get 6df data.
int get_num_meatool ()
Get number of measurement tools.
dtrack2_meatool_type get_meatool (int id)
Get 6dmt data.
int get_num_hand ()
Get number of fingertracking hands.
dtrack2_hand_type get_hand (int id)
Get gl data.
int get_num_marker ()
Get number of single markers.
dtrack2_marker_type get_marker (int index)
Get 3d data.
bool set_parameter (const std::string category, const std::string name, const std::string value)
Set DTrack2 parameter.
bool set_parameter (const std::string parameter)
Set DTrack2 parameter.
bool get_parameter (const std::string category, const std::string name, std::string &value)
Get DTrack2 parameter.
bool get_parameter (const std::string parameter, std::string &value)
Get DTrack2 parameter.
bool send_command (const std::string command)
Send DTrack2 command.
bool get_lasterror (int &errorcode)
Get last DTrack2 error code.
bool get_lasterror (std::string &errorstring)
Get last DTrack2 error code.
bool get_message ()
Get DTrack2 message.
std::string get_message_origin ()
Get origin of last DTrack2 message.
std::string get_message_status ()
Get status of last DTrack2 message.
unsigned int get_message_framenr ()
Get frame counter of last DTrack2 message.
unsigned int get_message_errorid ()
Get error id of last DTrack2 message.
std::string get_message_msg ()
Get message string of last DTrack2 message.
Detailed Description
Wrapper class for DTrack 2 SDK.
Definition at line 59 of file DTrack2.hpp.
Constructor & Destructor Documentation
DTrack2::DTrack2 (const std::string & server_host = "", unsigned short server_port = 50105, unsigned short data_port = 0, int data_bufsize = 20000, int data_timeout_us = 1000000, int server_timeout_us = 10000000)
Constructor.
Parameters:
[in] server_host TCP access to DTrack2 server: hostname or IP address of ARTtrack Controller, empty string if not used
[in] server_port TCP access to DTrack2 server: port number of ARTtrack Controller, default 50105
[in] data_port UDP port number to receive tracking data from ARTtrack Controller (0 if to be chosen)
[in] data_bufsize size of buffer for UDP packets (in bytes)
[in] data_timeout_us UDP timeout (receiving) in us (in micro second)
[in] server_timeout_us TCP timeout for access to DTrack2 server (in micro second; receiving and sending)
Definition at line 60 of file DTrack2.cpp.
References DTrackSDK::SYS_DTRACK_2.
DTrack2::~DTrack2 ()
Destructor.
Definition at line 71 of file DTrack2.cpp.
DTrack2::DTrack2 (const std::string & server_host = "", unsigned short server_port = 50105, unsigned short data_port = 0, int data_bufsize = 20000, int data_timeout_us = 1000000, int server_timeout_us = 10000000)
Constructor.
Parameters:
[in] server_host TCP access to DTrack2 server: hostname or IP address of ARTtrack Controller, empty string if not used
[in] server_port TCP access to DTrack2 server: port number of ARTtrack Controller, default 50105
[in] data_port UDP port number to receive tracking data from ARTtrack Controller (0 if to be chosen)
[in] data_bufsize size of buffer for UDP packets (in bytes)
[in] data_timeout_us UDP timeout (receiving) in us (in micro second)
[in] server_timeout_us TCP timeout for access to DTrack2 server (in micro second; receiving and sending)
DTrack2::~DTrack2 ()
Destructor.
DTrack2::DTrack2 (const std::string & server_host = "", unsigned short server_port = 50105, unsigned short data_port = 0, int data_bufsize = 20000, int data_timeout_us = 1000000, int server_timeout_us = 10000000)
Constructor.
Parameters:
[in] server_host TCP access to DTrack2 server: hostname or IP address of ARTtrack Controller, empty string if not used
[in] server_port TCP access to DTrack2 server: port number of ARTtrack Controller, default 50105
[in] data_port UDP port number to receive tracking data from ARTtrack Controller (0 if to be chosen)
[in] data_bufsize size of buffer for UDP packets (in bytes)
[in] data_timeout_us UDP timeout (receiving) in us (in micro second)
[in] server_timeout_us TCP timeout for access to DTrack2 server (in micro second; receiving and sending)
DTrack2::~DTrack2 ()
Destructor.
Member Function Documentation
bool DTrack2::valid (void)
Check if initialization was successfull.
Returns:
Valid?
Definition at line 82 of file DTrack2.cpp.
References DTrackSDK::isLocalDataPortValid().
Referenced by main().
unsigned short DTrack2::get_data_port ()
Get used UDP port number.
Returns:
local udp data port used for receiving tracking data
Definition at line 93 of file DTrack2.cpp.
References DTrackSDK::getDataPort().
Referenced by main().
bool DTrack2::data_timeout ()
Check last data receive error (timeout).
Returns:
timeout occured?
Definition at line 104 of file DTrack2.cpp.
References DTrackSDK::ERR_TIMEOUT, and DTrackSDK::getLastDataError().
Referenced by data_error_to_console(), and error_to_console().
bool DTrack2::data_neterror ()
Check last data receive error (net error).
Returns:
net error occured?
Definition at line 115 of file DTrack2.cpp.
References DTrackSDK::ERR_NET, and DTrackSDK::getLastDataError().
Referenced by data_error_to_console(), and error_to_console().
bool DTrack2::data_parseerror ()
Check last data receive error (parser).
Returns:
error occured while parsing tracking data?
Definition at line 126 of file DTrack2.cpp.
References DTrackSDK::ERR_PARSE, and DTrackSDK::getLastDataError().
Referenced by data_error_to_console(), and error_to_console().
bool DTrack2::server_noconnection ()
Check if connection to DTrack2 server is completely lost.
Returns:
connection lost?
Definition at line 137 of file DTrack2.cpp.
References DTrackSDK::isCommandInterfaceValid().
Referenced by command_error_to_console().
bool DTrack2::server_timeout ()
Check last command receive/send error (timeout).
Returns:
timeout occured?
Definition at line 148 of file DTrack2.cpp.
References DTrackSDK::ERR_TIMEOUT, and DTrackSDK::getLastServerError().
Referenced by command_error_to_console().
bool DTrack2::server_neterror ()
Check last command receive/send error (network).
Returns:
net error occured?
Definition at line 159 of file DTrack2.cpp.
References DTrackSDK::ERR_NET, and DTrackSDK::getLastServerError().
Referenced by command_error_to_console().
bool DTrack2::server_parseerror ()
Check last command receive/send error (parsing).
Returns:
error occured while parsing command data?
Definition at line 170 of file DTrack2.cpp.
References DTrackSDK::ERR_PARSE, and DTrackSDK::getLastServerError().
Referenced by command_error_to_console().
bool DTrack2::receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
Returns:
successful?
Definition at line 181 of file DTrack2.cpp.
References DTrackSDK_Datatypes::DTrack_Hand_Type_d::anglephalanx, DTrackSDK_Datatypes::DTrack_Hand_Type_f::anglephalanx, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::button, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::button, DTRACK_FLYSTICK_MAX_BUTTON, DTRACK_FLYSTICK_MAX_JOYSTICK, DTRACK_HAND_MAX_FINGER, DTRACK_MEATOOL_MAX_BUTTON, DTrackSDK_Datatypes::DTrack_Hand_Type_d::finger, DTrackSDK_Datatypes::DTrack_Hand_Type_f::finger, DTrackSDK::getBody(), DTrackSDK::getFlyStick(), DTrackSDK::getHand(), DTrackSDK::getMarker(), DTrackSDK::getMeaTool(), DTrackSDK::getNumBody(), DTrackSDK::getNumFlyStick(), DTrackSDK::getNumHand(), DTrackSDK::getNumMarker(), DTrackSDK::getNumMeaTool(), DTrackSDK_Datatypes::DTrack_Marker_Type_d::id, DTrackSDK_Datatypes::DTrack_Marker_Type_f::id, DTrackSDK_Datatypes::DTrack_Hand_Type_d::id, DTrackSDK_Datatypes::DTrack_Hand_Type_f::id, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::id, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::id, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::id, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::id, DTrackSDK_Datatypes::DTrack_Body_Type_d::id, DTrackSDK_Datatypes::DTrack_Body_Type_f::id, DTrackSDK::isLocalDataPortValid(), DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::joystick, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::joystick, DTrackSDK_Datatypes::DTrack_Hand_Type_d::lengthphalanx, DTrackSDK_Datatypes::DTrack_Hand_Type_f::lengthphalanx, DTrackSDK_Datatypes::DTrack_Marker_Type_d::loc, DTrackSDK_Datatypes::DTrack_Marker_Type_f::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_d::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_f::loc, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::loc, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::loc, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::loc, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::loc, DTrackSDK_Datatypes::DTrack_Body_Type_d::loc, DTrackSDK_Datatypes::DTrack_Body_Type_f::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_d::lr, DTrackSDK_Datatypes::DTrack_Hand_Type_f::lr, DTrackSDK_Datatypes::DTrack_Hand_Type_d::nfinger, DTrackSDK_Datatypes::DTrack_Hand_Type_f::nfinger, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::num_button, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::num_button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::num_button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::num_button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::num_joystick, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::num_joystick, DTrackSDK_Datatypes::DTrack_Marker_Type_d::quality, DTrackSDK_Datatypes::DTrack_Marker_Type_f::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_d::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_f::quality, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::quality, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::quality, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::quality, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::quality, DTrackSDK_Datatypes::DTrack_Body_Type_d::quality, DTrackSDK_Datatypes::DTrack_Body_Type_f::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_d::radiustip, DTrackSDK_Datatypes::DTrack_Hand_Type_f::radiustip, DTrackSDK::receive(), DTrackSDK_Datatypes::DTrack_Hand_Type_d::rot, DTrackSDK_Datatypes::DTrack_Hand_Type_f::rot, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::rot, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::rot, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::rot, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::rot, DTrackSDK_Datatypes::DTrack_Body_Type_d::rot, and DTrackSDK_Datatypes::DTrack_Body_Type_f::rot.
Referenced by main().
unsigned int DTrack2::get_framecounter ()
Get frame counter.
Refers to last received frame.
Returns:
frame counter
Definition at line 288 of file DTrack2.cpp.
References DTrackSDK::getFrameCounter().
Referenced by output_to_console().
double DTrack2::get_timestamp ()
Get timestamp.
Refers to last received frame.
Returns:
timestamp (-1 if information not available)
Definition at line 300 of file DTrack2.cpp.
References DTrackSDK::getTimeStamp().
Referenced by output_to_console().
int DTrack2::get_num_body ()
Get number of standard bodies.
Refers to last received frame.
Returns:
number of standard bodies
Definition at line 312 of file DTrack2.cpp.
Referenced by output_to_console().
dtrack2_body_type DTrack2::get_body (int id)
Get 6d data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_body - 1
Returns:
id-th standard body data.
Definition at line 325 of file DTrack2.cpp.
References DTrackSDK_Datatypes::DTrack_Body_Type_f::id, and DTrackSDK_Datatypes::DTrack_Body_Type_f::quality.
Referenced by output_to_console().
int DTrack2::get_num_flystick ()
Get number of flysticks.
Refers to last received frame.
Returns:
number of flysticks
Definition at line 344 of file DTrack2.cpp.
Referenced by output_to_console().
dtrack2_flystick_type DTrack2::get_flystick (int id)
Get 6df data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_flystick - 1
Returns:
id-th flystick data
Definition at line 357 of file DTrack2.cpp.
References DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::id, and DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::quality.
Referenced by output_to_console().
int DTrack2::get_num_meatool (void)
Get number of measurement tools.
Refers to last received frame.
Returns:
number of measurement tools
Definition at line 376 of file DTrack2.cpp.
Referenced by output_to_console().
dtrack2_meatool_type DTrack2::get_meatool (int id)
Get 6dmt data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_meatool - 1
Returns:
id-th measurement tool data
Definition at line 389 of file DTrack2.cpp.
References DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::id, and DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::quality.
Referenced by output_to_console().
int DTrack2::get_num_hand ()
Get number of fingertracking hands.
Refers to last received frame.
Returns:
number of fingertracking hands
Definition at line 408 of file DTrack2.cpp.
Referenced by output_to_console().
dtrack2_hand_type DTrack2::get_hand (int id)
Get gl data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_hand - 1
Returns:
id-th Fingertracking hand data.
Definition at line 421 of file DTrack2.cpp.
References DTrackSDK_Datatypes::DTrack_Hand_Type_f::id, and DTrackSDK_Datatypes::DTrack_Hand_Type_f::quality.
Referenced by output_to_console().
int DTrack2::get_num_marker ()
Get number of single markers.
Refers to last received frame.
Returns:
number of single markers
Definition at line 440 of file DTrack2.cpp.
Referenced by output_to_console().
dtrack2_marker_type DTrack2::get_marker (int index)
Get 3d data.
Refers to last received frame.
Parameters:
[in] index index, range 0 .. num_marker - 1
Returns:
id-th single marker data
Definition at line 453 of file DTrack2.cpp.
References DTrackSDK_Datatypes::DTrack_Marker_Type_f::id, and DTrackSDK_Datatypes::DTrack_Marker_Type_f::quality.
Referenced by output_to_console().
bool DTrack2::set_parameter (const std::string category, const std::string name, const std::string value)
Set DTrack2 parameter.
Parameters:
[in] category parameter category
[in] name parameter name
[in] value parameter value
Returns:
setting was successful (if not, a DTrack2 error message is available)
Definition at line 474 of file DTrack2.cpp.
bool DTrack2::set_parameter (const std::string parameter)
Set DTrack2 parameter.
Parameters:
[in] parameter total parameter (category, name and value; without starting "dtrack2 set ")
Returns:
setting was successful (if not, a DTrack2 error message is available)
Definition at line 486 of file DTrack2.cpp.
References send_command().
bool DTrack2::get_parameter (const std::string category, const std::string name, std::string & value)
Get DTrack2 parameter.
Parameters:
[in] category parameter category
[in] name parameter name
[out] value parameter value
Returns:
getting was successful (if not, a DTrack2 error message is available)
Definition at line 500 of file DTrack2.cpp.
bool DTrack2::get_parameter (const std::string parameter, std::string & value)
Get DTrack2 parameter.
Parameters:
[in] parameter total parameter (category and name; without starting "dtrack2 get ")
[out] value parameter value
Returns:
getting was successful (if not, a DTrack2 error message is available)
Definition at line 513 of file DTrack2.cpp.
References DTrackSDK::getParam().
bool DTrack2::send_command (const std::string command)
Send DTrack2 command.
Parameters:
[in] command command (without starting "dtrack2 ")
Returns:
command was successful and "dtrack2 ok" is received (if not, a DTrack2 error message is available)
Definition at line 525 of file DTrack2.cpp.
References DTrackSDK::sendDTrack2Command().
Referenced by main(), and set_parameter().
bool DTrack2::get_lasterror (int & errorcode)
Get last DTrack2 error code.
Parameters:
[out] errorcode error as code number
Returns:
error code was available, otherwise last command was successful
Definition at line 537 of file DTrack2.cpp.
References DTrackSDK::getLastDTrackError().
Referenced by command_error_to_console().
bool DTrack2::get_lasterror (std::string & errorstring)
Get last DTrack2 error code.
Parameters:
[out] errorstring error as string
Returns:
error code was available, otherwise last command was successful
Definition at line 550 of file DTrack2.cpp.
References DTrackSDK::getLastDTrackError(), and DTrackSDK::getLastDTrackErrorDescription().
bool DTrack2::get_message ()
Get DTrack2 message.
Returns:
message was available
Definition at line 564 of file DTrack2.cpp.
References DTrackSDK::getMessage().
Referenced by messages_to_console().
std::string DTrack2::get_message_origin ()
Get origin of last DTrack2 message.
Returns:
origin
Definition at line 575 of file DTrack2.cpp.
References DTrackSDK::getMessageOrigin().
std::string DTrack2::get_message_status ()
Get status of last DTrack2 message.
Returns:
status
Definition at line 586 of file DTrack2.cpp.
References DTrackSDK::getMessageStatus().
Referenced by messages_to_console().
unsigned int DTrack2::get_message_framenr ()
Get frame counter of last DTrack2 message.
Returns:
frame counter
Definition at line 597 of file DTrack2.cpp.
References DTrackSDK::getMessageFrameNr().
unsigned int DTrack2::get_message_errorid ()
Get error id of last DTrack2 message.
Returns:
error id
Definition at line 608 of file DTrack2.cpp.
References DTrackSDK::getMessageErrorId().
std::string DTrack2::get_message_msg ()
Get message string of last DTrack2 message.
Returns:
mesage string
Definition at line 619 of file DTrack2.cpp.
References DTrackSDK::getMessageMsg().
Referenced by messages_to_console().
bool DTrack2::valid ()
Check if initialization was successfull.
Returns:
Valid?
unsigned short DTrack2::get_data_port ()
Get used UDP port number.
Returns:
local udp data port used for receiving tracking data
bool DTrack2::data_timeout ()
Check last data receive error (timeout).
Returns:
timeout occured?
bool DTrack2::data_neterror ()
Check last data receive error (net error).
Returns:
net error occured?
bool DTrack2::data_parseerror ()
Check last data receive error (parser).
Returns:
error occured while parsing tracking data?
bool DTrack2::server_noconnection ()
Check if connection to DTrack2 server is completely lost.
Returns:
connection lost?
bool DTrack2::server_timeout ()
Check last command receive/send error (timeout).
Returns:
timeout occured?
bool DTrack2::server_neterror ()
Check last command receive/send error (network).
Returns:
net error occured?
bool DTrack2::server_parseerror ()
Check last command receive/send error (parsing).
Returns:
error occured while parsing command data?
bool DTrack2::receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
Returns:
successful?
unsigned int DTrack2::get_framecounter ()
Get frame counter.
Refers to last received frame.
Returns:
frame counter
double DTrack2::get_timestamp ()
Get timestamp.
Refers to last received frame.
Returns:
timestamp (-1 if information not available)
int DTrack2::get_num_body ()
Get number of standard bodies.
Refers to last received frame.
Returns:
number of standard bodies
dtrack2_body_type DTrack2::get_body (int id)
Get 6d data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_body - 1
Returns:
id-th standard body data.
int DTrack2::get_num_flystick ()
Get number of flysticks.
Refers to last received frame.
Returns:
number of flysticks
dtrack2_flystick_type DTrack2::get_flystick (int id)
Get 6df data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_flystick - 1
Returns:
id-th flystick data
int DTrack2::get_num_meatool ()
Get number of measurement tools.
Refers to last received frame.
Returns:
number of measurement tools
dtrack2_meatool_type DTrack2::get_meatool (int id)
Get 6dmt data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_meatool - 1
Returns:
id-th measurement tool data
int DTrack2::get_num_hand ()
Get number of fingertracking hands.
Refers to last received frame.
Returns:
number of fingertracking hands
dtrack2_hand_type DTrack2::get_hand (int id)
Get gl data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_hand - 1
Returns:
id-th Fingertracking hand data.
int DTrack2::get_num_marker ()
Get number of single markers.
Refers to last received frame.
Returns:
number of single markers
dtrack2_marker_type DTrack2::get_marker (int index)
Get 3d data.
Refers to last received frame.
Parameters:
[in] index index, range 0 .. num_marker - 1
Returns:
id-th single marker data
bool DTrack2::set_parameter (const std::string category, const std::string name, const std::string value)
Set DTrack2 parameter.
Parameters:
[in] category parameter category
[in] name parameter name
[in] value parameter value
Returns:
setting was successful (if not, a DTrack2 error message is available)
bool DTrack2::set_parameter (const std::string parameter)
Set DTrack2 parameter.
Parameters:
[in] parameter total parameter (category, name and value; without starting "dtrack2 set ")
Returns:
setting was successful (if not, a DTrack2 error message is available)
bool DTrack2::get_parameter (const std::string category, const std::string name, std::string & value)
Get DTrack2 parameter.
Parameters:
[in] category parameter category
[in] name parameter name
[out] value parameter value
Returns:
getting was successful (if not, a DTrack2 error message is available)
bool DTrack2::get_parameter (const std::string parameter, std::string & value)
Get DTrack2 parameter.
Parameters:
[in] parameter total parameter (category and name; without starting "dtrack2 get ")
[out] value parameter value
Returns:
getting was successful (if not, a DTrack2 error message is available)
bool DTrack2::send_command (const std::string command)
Send DTrack2 command.
Parameters:
[in] command command (without starting "dtrack2 ")
Returns:
command was successful and "dtrack2 ok" is received (if not, a DTrack2 error message is available)
bool DTrack2::get_lasterror (int & errorcode)
Get last DTrack2 error code.
Parameters:
[out] errorcode error as code number
Returns:
error code was available, otherwise last command was successful
bool DTrack2::get_lasterror (std::string & errorstring)
Get last DTrack2 error code.
Parameters:
[out] errorstring error as string
Returns:
error code was available, otherwise last command was successful
bool DTrack2::get_message ()
Get DTrack2 message.
Returns:
message was available
std::string DTrack2::get_message_origin ()
Get origin of last DTrack2 message.
Returns:
origin
std::string DTrack2::get_message_status ()
Get status of last DTrack2 message.
Returns:
status
unsigned int DTrack2::get_message_framenr ()
Get frame counter of last DTrack2 message.
Returns:
frame counter
unsigned int DTrack2::get_message_errorid ()
Get error id of last DTrack2 message.
Returns:
error id
std::string DTrack2::get_message_msg ()
Get message string of last DTrack2 message.
Returns:
mesage string
bool DTrack2::valid ()
Check if initialization was successfull.
Returns:
Valid?
unsigned short DTrack2::get_data_port ()
Get used UDP port number.
Returns:
local udp data port used for receiving tracking data
bool DTrack2::data_timeout ()
Check last data receive error (timeout).
Returns:
timeout occured?
bool DTrack2::data_neterror ()
Check last data receive error (net error).
Returns:
net error occured?
bool DTrack2::data_parseerror ()
Check last data receive error (parser).
Returns:
error occured while parsing tracking data?
bool DTrack2::server_noconnection ()
Check if connection to DTrack2 server is completely lost.
Returns:
connection lost?
bool DTrack2::server_timeout ()
Check last command receive/send error (timeout).
Returns:
timeout occured?
bool DTrack2::server_neterror ()
Check last command receive/send error (network).
Returns:
net error occured?
bool DTrack2::server_parseerror ()
Check last command receive/send error (parsing).
Returns:
error occured while parsing command data?
bool DTrack2::receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
Returns:
successful?
unsigned int DTrack2::get_framecounter ()
Get frame counter.
Refers to last received frame.
Returns:
frame counter
double DTrack2::get_timestamp ()
Get timestamp.
Refers to last received frame.
Returns:
timestamp (-1 if information not available)
int DTrack2::get_num_body ()
Get number of standard bodies.
Refers to last received frame.
Returns:
number of standard bodies
dtrack2_body_type DTrack2::get_body (int id)
Get 6d data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_body - 1
Returns:
id-th standard body data.
int DTrack2::get_num_flystick ()
Get number of flysticks.
Refers to last received frame.
Returns:
number of flysticks
dtrack2_flystick_type DTrack2::get_flystick (int id)
Get 6df data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_flystick - 1
Returns:
id-th flystick data
int DTrack2::get_num_meatool ()
Get number of measurement tools.
Refers to last received frame.
Returns:
number of measurement tools
dtrack2_meatool_type DTrack2::get_meatool (int id)
Get 6dmt data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_meatool - 1
Returns:
id-th measurement tool data
int DTrack2::get_num_hand ()
Get number of fingertracking hands.
Refers to last received frame.
Returns:
number of fingertracking hands
dtrack2_hand_type DTrack2::get_hand (int id)
Get gl data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_hand - 1
Returns:
id-th Fingertracking hand data.
int DTrack2::get_num_marker ()
Get number of single markers.
Refers to last received frame.
Returns:
number of single markers
dtrack2_marker_type DTrack2::get_marker (int index)
Get 3d data.
Refers to last received frame.
Parameters:
[in] index index, range 0 .. num_marker - 1
Returns:
id-th single marker data
bool DTrack2::set_parameter (const std::string category, const std::string name, const std::string value)
Set DTrack2 parameter.
Parameters:
[in] category parameter category
[in] name parameter name
[in] value parameter value
Returns:
setting was successful (if not, a DTrack2 error message is available)
bool DTrack2::set_parameter (const std::string parameter)
Set DTrack2 parameter.
Parameters:
[in] parameter total parameter (category, name and value; without starting "dtrack2 set ")
Returns:
setting was successful (if not, a DTrack2 error message is available)
bool DTrack2::get_parameter (const std::string category, const std::string name, std::string & value)
Get DTrack2 parameter.
Parameters:
[in] category parameter category
[in] name parameter name
[out] value parameter value
Returns:
getting was successful (if not, a DTrack2 error message is available)
bool DTrack2::get_parameter (const std::string parameter, std::string & value)
Get DTrack2 parameter.
Parameters:
[in] parameter total parameter (category and name; without starting "dtrack2 get ")
[out] value parameter value
Returns:
getting was successful (if not, a DTrack2 error message is available)
bool DTrack2::send_command (const std::string command)
Send DTrack2 command.
Parameters:
[in] command command (without starting "dtrack2 ")
Returns:
command was successful and "dtrack2 ok" is received (if not, a DTrack2 error message is available)
bool DTrack2::get_lasterror (int & errorcode)
Get last DTrack2 error code.
Parameters:
[out] errorcode error as code number
Returns:
error code was available, otherwise last command was successful
bool DTrack2::get_lasterror (std::string & errorstring)
Get last DTrack2 error code.
Parameters:
[out] errorstring error as string
Returns:
error code was available, otherwise last command was successful
bool DTrack2::get_message ()
Get DTrack2 message.
Returns:
message was available
std::string DTrack2::get_message_origin ()
Get origin of last DTrack2 message.
Returns:
origin
std::string DTrack2::get_message_status ()
Get status of last DTrack2 message.
Returns:
status
unsigned int DTrack2::get_message_framenr ()
Get frame counter of last DTrack2 message.
Returns:
frame counter
unsigned int DTrack2::get_message_errorid ()
Get error id of last DTrack2 message.
Returns:
error id
std::string DTrack2::get_message_msg ()
Get message string of last DTrack2 message.
Returns:
mesage string
The documentation for this class was generated from the following files:
Compatibility/DTrack2/DTrack2.hpp
ship_it/DTrackSDK_v2.1.0/Compatibility/DTrack2/DTrack2.hpp
ship_it/DTrackSDK_v2.2.0/Compatibility/DTrack2/DTrack2.hpp
Compatibility/DTrack2/DTrack2.cpp
ship_it/DTrackSDK_v2.1.0/Compatibility/DTrack2/DTrack2.cpp
ship_it/DTrackSDK_v2.2.0/Compatibility/DTrack2/DTrack2.cpp