Doxygen: DTrack Class Reference
DTrack Class Reference
Wrapper class for DTrack SDK.
#include <DTrack.hpp>
Public Member Functions
DTrack (int data_port=5000, const char *remote_host=NULL, int remote_port=0, int data_bufsize=20000, int data_timeout_us=1000000)
Constructor.
~DTrack (void)
Destructor.
bool valid (void)
Check if initialization was successfull.
bool timeout ()
Check last receive/send error (timeout).
bool udperror ()
Check last receive/send error (udp error).
bool parseerror ()
Check last receive/send error (parser).
bool receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
unsigned int get_framecounter ()
Get frame counter.
double get_timestamp ()
Get timestamp.
int get_num_body ()
Get number of standard bodies.
dtrack_body_type get_body (int id)
Get 6d data.
int get_num_flystick ()
Get number of flysticks.
dtrack_flystick_type get_flystick (int id)
Get 6df data.
int get_num_meatool ()
Get number of measurement tools.
dtrack_meatool_type get_meatool (int id)
Get 6dmt data.
int get_num_hand ()
Get number of fingertracking hands.
dtrack_hand_type get_hand (int id)
Get gl data.
int get_num_marker ()
Get number of single markers.
dtrack_marker_type get_marker (int index)
Get 3d data.
bool cmd_cameras (bool onoff)
Control cameras by remote commands to DTrack (UDP; ASCII protocol; Default off).
bool cmd_tracking (bool onoff)
Control tracking calculation by remote commands to DTrack (UDP, ASCII protocol; Default: on).
bool cmd_sending_data (bool onoff)
Control sending of UDP output data by remote commands to DTrack (UDP, ASCII protocol; Default: on).
bool cmd_sending_fixed_data (int frames)
Control sending of a fixed number of UDP output data frames by remote commands to DTrack (UDP, ASCII protocol).
DTrack (int data_port=5000, const char *remote_host=NULL, int remote_port=0, int data_bufsize=20000, int data_timeout_us=1000000)
Constructor.
~DTrack (void)
Destructor.
bool valid (void)
Check if initialization was successfull.
bool timeout ()
Check last receive/send error (timeout).
bool udperror ()
Check last receive/send error (udp error).
bool parseerror ()
Check last receive/send error (parser).
bool receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
unsigned int get_framecounter ()
Get frame counter.
double get_timestamp ()
Get timestamp.
int get_num_body ()
Get number of standard bodies.
dtrack_body_type get_body (int id)
Get 6d data.
int get_num_flystick ()
Get number of flysticks.
dtrack_flystick_type get_flystick (int id)
Get 6df data.
int get_num_meatool ()
Get number of measurement tools.
dtrack_meatool_type get_meatool (int id)
Get 6dmt data.
int get_num_hand ()
Get number of fingertracking hands.
dtrack_hand_type get_hand (int id)
Get gl data.
int get_num_marker ()
Get number of single markers.
dtrack_marker_type get_marker (int index)
Get 3d data.
bool cmd_cameras (bool onoff)
Control cameras by remote commands to DTrack (UDP; ASCII protocol; Default off).
bool cmd_tracking (bool onoff)
Control tracking calculation by remote commands to DTrack (UDP, ASCII protocol; Default: on).
bool cmd_sending_data (bool onoff)
Control sending of UDP output data by remote commands to DTrack (UDP, ASCII protocol; Default: on).
bool cmd_sending_fixed_data (int frames)
Control sending of a fixed number of UDP output data frames by remote commands to DTrack (UDP, ASCII protocol).
DTrack (int data_port=5000, const char *remote_host=NULL, int remote_port=0, int data_bufsize=20000, int data_timeout_us=1000000)
Constructor.
~DTrack (void)
Destructor.
bool valid (void)
Check if initialization was successfull.
bool timeout ()
Check last receive/send error (timeout).
bool udperror ()
Check last receive/send error (udp error).
bool parseerror ()
Check last receive/send error (parser).
bool receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
unsigned int get_framecounter ()
Get frame counter.
double get_timestamp ()
Get timestamp.
int get_num_body ()
Get number of standard bodies.
dtrack_body_type get_body (int id)
Get 6d data.
int get_num_flystick ()
Get number of flysticks.
dtrack_flystick_type get_flystick (int id)
Get 6df data.
int get_num_meatool ()
Get number of measurement tools.
dtrack_meatool_type get_meatool (int id)
Get 6dmt data.
int get_num_hand ()
Get number of fingertracking hands.
dtrack_hand_type get_hand (int id)
Get gl data.
int get_num_marker ()
Get number of single markers.
dtrack_marker_type get_marker (int index)
Get 3d data.
bool cmd_cameras (bool onoff)
Control cameras by remote commands to DTrack (UDP; ASCII protocol; Default off).
bool cmd_tracking (bool onoff)
Control tracking calculation by remote commands to DTrack (UDP, ASCII protocol; Default: on).
bool cmd_sending_data (bool onoff)
Control sending of UDP output data by remote commands to DTrack (UDP, ASCII protocol; Default: on).
bool cmd_sending_fixed_data (int frames)
Control sending of a fixed number of UDP output data frames by remote commands to DTrack (UDP, ASCII protocol).
Detailed Description
Wrapper class for DTrack SDK.
Definition at line 63 of file DTrack.hpp.
Constructor & Destructor Documentation
DTrack::DTrack (int data_port = 5000, const char * remote_host = NULL, int remote_port = 0, int data_bufsize = 20000, int data_timeout_us = 1000000)
Constructor.
Parameters:
[in] data_port UDP port number to receive data from DTrack
[in] remote_host DTrack remote control: hostname or IP address of DTrack PC (NULL if not used)
[in] remote_port port number of DTrack remote control (0 if not used)
[in] data_bufsize size of buffer for UDP packets (in bytes)
[in] data_timeout_us UDP timeout (receiving and sending) in us (micro second)
Definition at line 48 of file DTrack.cpp.
References DTrackSDK::SYS_DTRACK_UNKNOWN.
DTrack::~DTrack (void)
Destructor.
Definition at line 66 of file DTrack.cpp.
DTrack::DTrack (int data_port = 5000, const char * remote_host = NULL, int remote_port = 0, int data_bufsize = 20000, int data_timeout_us = 1000000)
Constructor.
Parameters:
[in] data_port UDP port number to receive data from DTrack
[in] remote_host DTrack remote control: hostname or IP address of DTrack PC (NULL if not used)
[in] remote_port port number of DTrack remote control (0 if not used)
[in] data_bufsize size of buffer for UDP packets (in bytes)
[in] data_timeout_us UDP timeout (receiving and sending) in us (micro second)
DTrack::~DTrack (void)
Destructor.
DTrack::DTrack (int data_port = 5000, const char * remote_host = NULL, int remote_port = 0, int data_bufsize = 20000, int data_timeout_us = 1000000)
Constructor.
Parameters:
[in] data_port UDP port number to receive data from DTrack
[in] remote_host DTrack remote control: hostname or IP address of DTrack PC (NULL if not used)
[in] remote_port port number of DTrack remote control (0 if not used)
[in] data_bufsize size of buffer for UDP packets (in bytes)
[in] data_timeout_us UDP timeout (receiving and sending) in us (micro second)
DTrack::~DTrack (void)
Destructor.
Member Function Documentation
bool DTrack::valid (void)
Check if initialization was successfull.
Returns:
Valid?
Definition at line 77 of file DTrack.cpp.
References DTrackSDK::isLocalDataPortValid().
Referenced by cmd_cameras(), cmd_sending_data(), cmd_sending_fixed_data(), cmd_tracking(), and main().
bool DTrack::timeout ()
Check last receive/send error (timeout).
Returns:
timeout occured?
Definition at line 88 of file DTrack.cpp.
References DTrackSDK::ERR_TIMEOUT, and DTrackSDK::getLastDataError().
Referenced by error_to_console().
bool DTrack::udperror ()
Check last receive/send error (udp error).
Returns:
udp error occured?
Definition at line 99 of file DTrack.cpp.
References DTrackSDK::ERR_NET, and DTrackSDK::getLastDataError().
Referenced by error_to_console().
bool DTrack::parseerror ()
Check last receive/send error (parser).
Returns:
error occured while parsing tracking data?
Definition at line 110 of file DTrack.cpp.
References DTrackSDK::ERR_PARSE, and DTrackSDK::getLastDataError().
Referenced by error_to_console().
bool DTrack::receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
Returns:
successful?
Definition at line 121 of file DTrack.cpp.
References DTrackSDK_Datatypes::DTrack_Hand_Type_d::anglephalanx, DTrackSDK_Datatypes::DTrack_Hand_Type_f::anglephalanx, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::button, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::button, DTRACK_FLYSTICK_MAX_BUTTON, DTRACK_FLYSTICK_MAX_JOYSTICK, DTRACK_HAND_MAX_FINGER, DTRACK_MEATOOL_MAX_BUTTON, DTrackSDK_Datatypes::DTrack_Hand_Type_d::finger, DTrackSDK_Datatypes::DTrack_Hand_Type_f::finger, DTrackSDK::getBody(), DTrackSDK::getFlyStick(), DTrackSDK::getHand(), DTrackSDK::getMarker(), DTrackSDK::getMeaTool(), DTrackSDK::getNumBody(), DTrackSDK::getNumFlyStick(), DTrackSDK::getNumHand(), DTrackSDK::getNumMarker(), DTrackSDK::getNumMeaTool(), DTrackSDK_Datatypes::DTrack_Marker_Type_d::id, DTrackSDK_Datatypes::DTrack_Marker_Type_f::id, DTrackSDK_Datatypes::DTrack_Hand_Type_d::id, DTrackSDK_Datatypes::DTrack_Hand_Type_f::id, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::id, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::id, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::id, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::id, DTrackSDK_Datatypes::DTrack_Body_Type_d::id, DTrackSDK_Datatypes::DTrack_Body_Type_f::id, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::joystick, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::joystick, DTrackSDK_Datatypes::DTrack_Hand_Type_d::lengthphalanx, DTrackSDK_Datatypes::DTrack_Hand_Type_f::lengthphalanx, DTrackSDK_Datatypes::DTrack_Marker_Type_d::loc, DTrackSDK_Datatypes::DTrack_Marker_Type_f::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_d::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_f::loc, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::loc, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::loc, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::loc, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::loc, DTrackSDK_Datatypes::DTrack_Body_Type_d::loc, DTrackSDK_Datatypes::DTrack_Body_Type_f::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_d::lr, DTrackSDK_Datatypes::DTrack_Hand_Type_f::lr, DTrackSDK_Datatypes::DTrack_Hand_Type_d::nfinger, DTrackSDK_Datatypes::DTrack_Hand_Type_f::nfinger, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::num_button, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::num_button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::num_button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::num_button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::num_joystick, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::num_joystick, DTrackSDK_Datatypes::DTrack_Marker_Type_d::quality, DTrackSDK_Datatypes::DTrack_Marker_Type_f::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_d::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_f::quality, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::quality, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::quality, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::quality, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::quality, DTrackSDK_Datatypes::DTrack_Body_Type_d::quality, DTrackSDK_Datatypes::DTrack_Body_Type_f::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_d::radiustip, DTrackSDK_Datatypes::DTrack_Hand_Type_f::radiustip, DTrackSDK::receive(), DTrackSDK_Datatypes::DTrack_Hand_Type_d::rot, DTrackSDK_Datatypes::DTrack_Hand_Type_f::rot, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::rot, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::rot, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::rot, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::rot, DTrackSDK_Datatypes::DTrack_Body_Type_d::rot, and DTrackSDK_Datatypes::DTrack_Body_Type_f::rot.
Referenced by main().
unsigned int DTrack::get_framecounter ()
Get frame counter.
Refers to last received frame.
Returns:
frame counter
Definition at line 226 of file DTrack.cpp.
References DTrackSDK::getFrameCounter().
Referenced by output_to_console().
double DTrack::get_timestamp ()
Get timestamp.
Refers to last received frame.
Returns:
timestamp (-1 if information not available)
Definition at line 238 of file DTrack.cpp.
References DTrackSDK::getTimeStamp().
Referenced by output_to_console().
int DTrack::get_num_body ()
Get number of standard bodies.
Refers to last received frame.
Returns:
number of standard bodies
Definition at line 250 of file DTrack.cpp.
Referenced by output_to_console().
dtrack_body_type DTrack::get_body (int id)
Get 6d data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_body - 1
Returns:
id-th standard body data.
Definition at line 263 of file DTrack.cpp.
References DTrackSDK_Datatypes::DTrack_Body_Type_f::id, and DTrackSDK_Datatypes::DTrack_Body_Type_f::quality.
Referenced by output_to_console().
int DTrack::get_num_flystick ()
Get number of flysticks.
Refers to last received frame.
Returns:
number of flysticks
Definition at line 283 of file DTrack.cpp.
Referenced by output_to_console().
dtrack_flystick_type DTrack::get_flystick (int id)
Get 6df data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_flystick - 1
Returns:
id-th flystick data
Definition at line 296 of file DTrack.cpp.
References DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::id, and DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::quality.
Referenced by output_to_console().
int DTrack::get_num_meatool ()
Get number of measurement tools.
Refers to last received frame.
Returns:
number of measurement tools
Definition at line 316 of file DTrack.cpp.
Referenced by output_to_console().
dtrack_meatool_type DTrack::get_meatool (int id)
Get 6dmt data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_meatool - 1
Returns:
id-th measurement tool data
Definition at line 329 of file DTrack.cpp.
References DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::id, and DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::quality.
Referenced by output_to_console().
int DTrack::get_num_hand ()
Get number of fingertracking hands.
Refers to last received frame.
Returns:
number of fingertracking hands
Definition at line 349 of file DTrack.cpp.
Referenced by output_to_console().
dtrack_hand_type DTrack::get_hand (int id)
Get gl data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_hand - 1
Returns:
id-th Fingertracking hand data.
Definition at line 362 of file DTrack.cpp.
References DTrackSDK_Datatypes::DTrack_Hand_Type_f::id, and DTrackSDK_Datatypes::DTrack_Hand_Type_f::quality.
Referenced by output_to_console().
int DTrack::get_num_marker ()
Get number of single markers.
Refers to last received frame.
Returns:
number of single markers
Definition at line 381 of file DTrack.cpp.
Referenced by output_to_console().
dtrack_marker_type DTrack::get_marker (int index)
Get 3d data.
Refers to last received frame.
Parameters:
[in] index index, range 0 .. num_marker - 1
Returns:
id-th single marker data
Definition at line 394 of file DTrack.cpp.
References DTrackSDK_Datatypes::DTrack_Marker_Type_f::id, and DTrackSDK_Datatypes::DTrack_Marker_Type_f::quality.
Referenced by output_to_console().
bool DTrack::cmd_cameras (bool onoff)
Control cameras by remote commands to DTrack (UDP; ASCII protocol; Default off).
Parameters:
[in] onoff switch on/off
Returns:
sending of remote commands was successfull
Definition at line 413 of file DTrack.cpp.
References DTrackSDK::sendCommand(), and valid().
Referenced by main().
bool DTrack::cmd_tracking (bool onoff)
Control tracking calculation by remote commands to DTrack (UDP, ASCII protocol; Default: on).
Parameters:
[in] onoff Switch function (1 on, 0 off)
Returns:
sending of remote commands was successfull (1 yes, 0 no)
Definition at line 449 of file DTrack.cpp.
References DTrackSDK::sendCommand(), and valid().
Referenced by main().
bool DTrack::cmd_sending_data (bool onoff)
Control sending of UDP output data by remote commands to DTrack (UDP, ASCII protocol; Default: on).
Parameters:
[in] onoff Switch function (1 on, 0 off)
Returns:
sending of remote commands was successfull (1 yes, 0 no)
Definition at line 479 of file DTrack.cpp.
References DTrackSDK::sendCommand(), and valid().
Referenced by main().
bool DTrack::cmd_sending_fixed_data (int frames)
Control sending of a fixed number of UDP output data frames by remote commands to DTrack (UDP, ASCII protocol).
Parameters:
[in] frames Number of frames
Returns:
sending of remote commands was successfull (1 yes, 0 no)
Definition at line 501 of file DTrack.cpp.
References DTrackSDK::sendCommand(), and valid().
bool DTrack::valid (void)
Check if initialization was successfull.
Returns:
Valid?
bool DTrack::timeout ()
Check last receive/send error (timeout).
Returns:
timeout occured?
bool DTrack::udperror ()
Check last receive/send error (udp error).
Returns:
udp error occured?
bool DTrack::parseerror ()
Check last receive/send error (parser).
Returns:
error occured while parsing tracking data?
bool DTrack::receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
Returns:
successful?
unsigned int DTrack::get_framecounter ()
Get frame counter.
Refers to last received frame.
Returns:
frame counter
double DTrack::get_timestamp ()
Get timestamp.
Refers to last received frame.
Returns:
timestamp (-1 if information not available)
int DTrack::get_num_body ()
Get number of standard bodies.
Refers to last received frame.
Returns:
number of standard bodies
dtrack_body_type DTrack::get_body (int id)
Get 6d data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_body - 1
Returns:
id-th standard body data.
int DTrack::get_num_flystick ()
Get number of flysticks.
Refers to last received frame.
Returns:
number of flysticks
dtrack_flystick_type DTrack::get_flystick (int id)
Get 6df data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_flystick - 1
Returns:
id-th flystick data
int DTrack::get_num_meatool ()
Get number of measurement tools.
Refers to last received frame.
Returns:
number of measurement tools
dtrack_meatool_type DTrack::get_meatool (int id)
Get 6dmt data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_meatool - 1
Returns:
id-th measurement tool data
int DTrack::get_num_hand ()
Get number of fingertracking hands.
Refers to last received frame.
Returns:
number of fingertracking hands
dtrack_hand_type DTrack::get_hand (int id)
Get gl data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_hand - 1
Returns:
id-th Fingertracking hand data.
int DTrack::get_num_marker ()
Get number of single markers.
Refers to last received frame.
Returns:
number of single markers
dtrack_marker_type DTrack::get_marker (int index)
Get 3d data.
Refers to last received frame.
Parameters:
[in] index index, range 0 .. num_marker - 1
Returns:
id-th single marker data
bool DTrack::cmd_cameras (bool onoff)
Control cameras by remote commands to DTrack (UDP; ASCII protocol; Default off).
Parameters:
[in] onoff switch on/off
Returns:
sending of remote commands was successfull
bool DTrack::cmd_tracking (bool onoff)
Control tracking calculation by remote commands to DTrack (UDP, ASCII protocol; Default: on).
Parameters:
[in] onoff Switch function (1 on, 0 off)
Returns:
sending of remote commands was successfull (1 yes, 0 no)
bool DTrack::cmd_sending_data (bool onoff)
Control sending of UDP output data by remote commands to DTrack (UDP, ASCII protocol; Default: on).
Parameters:
[in] onoff Switch function (1 on, 0 off)
Returns:
sending of remote commands was successfull (1 yes, 0 no)
bool DTrack::cmd_sending_fixed_data (int frames)
Control sending of a fixed number of UDP output data frames by remote commands to DTrack (UDP, ASCII protocol).
Parameters:
[in] frames Number of frames
Returns:
sending of remote commands was successfull (1 yes, 0 no)
bool DTrack::valid (void)
Check if initialization was successfull.
Returns:
Valid?
bool DTrack::timeout ()
Check last receive/send error (timeout).
Returns:
timeout occured?
bool DTrack::udperror ()
Check last receive/send error (udp error).
Returns:
udp error occured?
bool DTrack::parseerror ()
Check last receive/send error (parser).
Returns:
error occured while parsing tracking data?
bool DTrack::receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
Returns:
successful?
unsigned int DTrack::get_framecounter ()
Get frame counter.
Refers to last received frame.
Returns:
frame counter
double DTrack::get_timestamp ()
Get timestamp.
Refers to last received frame.
Returns:
timestamp (-1 if information not available)
int DTrack::get_num_body ()
Get number of standard bodies.
Refers to last received frame.
Returns:
number of standard bodies
dtrack_body_type DTrack::get_body (int id)
Get 6d data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_body - 1
Returns:
id-th standard body data.
int DTrack::get_num_flystick ()
Get number of flysticks.
Refers to last received frame.
Returns:
number of flysticks
dtrack_flystick_type DTrack::get_flystick (int id)
Get 6df data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_flystick - 1
Returns:
id-th flystick data
int DTrack::get_num_meatool ()
Get number of measurement tools.
Refers to last received frame.
Returns:
number of measurement tools
dtrack_meatool_type DTrack::get_meatool (int id)
Get 6dmt data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_meatool - 1
Returns:
id-th measurement tool data
int DTrack::get_num_hand ()
Get number of fingertracking hands.
Refers to last received frame.
Returns:
number of fingertracking hands
dtrack_hand_type DTrack::get_hand (int id)
Get gl data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. num_hand - 1
Returns:
id-th Fingertracking hand data.
int DTrack::get_num_marker ()
Get number of single markers.
Refers to last received frame.
Returns:
number of single markers
dtrack_marker_type DTrack::get_marker (int index)
Get 3d data.
Refers to last received frame.
Parameters:
[in] index index, range 0 .. num_marker - 1
Returns:
id-th single marker data
bool DTrack::cmd_cameras (bool onoff)
Control cameras by remote commands to DTrack (UDP; ASCII protocol; Default off).
Parameters:
[in] onoff switch on/off
Returns:
sending of remote commands was successfull
bool DTrack::cmd_tracking (bool onoff)
Control tracking calculation by remote commands to DTrack (UDP, ASCII protocol; Default: on).
Parameters:
[in] onoff Switch function (1 on, 0 off)
Returns:
sending of remote commands was successfull (1 yes, 0 no)
bool DTrack::cmd_sending_data (bool onoff)
Control sending of UDP output data by remote commands to DTrack (UDP, ASCII protocol; Default: on).
Parameters:
[in] onoff Switch function (1 on, 0 off)
Returns:
sending of remote commands was successfull (1 yes, 0 no)
bool DTrack::cmd_sending_fixed_data (int frames)
Control sending of a fixed number of UDP output data frames by remote commands to DTrack (UDP, ASCII protocol).
Parameters:
[in] frames Number of frames
Returns:
sending of remote commands was successfull (1 yes, 0 no)
The documentation for this class was generated from the following files:
Compatibility/DTrack/DTrack.hpp
ship_it/DTrackSDK_v2.1.0/Compatibility/DTrack/DTrack.hpp
ship_it/DTrackSDK_v2.2.0/Compatibility/DTrack/DTrack.hpp
Compatibility/DTrack/DTrack.cpp
ship_it/DTrackSDK_v2.1.0/Compatibility/DTrack/DTrack.cpp
ship_it/DTrackSDK_v2.2.0/Compatibility/DTrack/DTrack.cpp