Doxygen: ship_it/DTrackSDK_v2.2.0/Compatibility/DTrackLib/example_without_remote_control.cpp File Reference
example_without_remote_control.cpp File Reference
#include "DTracklib.hpp"
#include <iostream>
#include <sstream>
#include <stdlib.h>
#include <stdio.h>
Functions
static void output_to_console ()
Prints current tracking data to console.
static bool error_to_console ()
Prints error messages to console.
int main (int argc, char **argv)
Main.
Variables
static DTracklib * dt = NULL
Function Documentation
static bool error_to_console () [static]
Prints error messages to console.
Returns:
No error occured?
Definition at line 130 of file example_without_remote_control.cpp.
References DTracklib::parseerror(), DTracklib::timeout(), and DTracklib::udperror().
int main (int argc, char ** argv)
Main.
Definition at line 154 of file example_without_remote_control.cpp.
References error_to_console(), output_to_console(), DTracklib::receive(), and DTracklib::valid().
static void output_to_console () [static]
Prints current tracking data to console.
Definition at line 45 of file example_without_remote_control.cpp.
References dtracklib_flystick_type::ang, DTrackSDK_Datatypes::DTrack_Hand_Type_f::anglephalanx, dtracklib_meatool_type::bt, dtracklib_flystick_type::bt, DTrackSDK_Datatypes::DTrack_Hand_Type_f::finger, DTracklib::get_body(), DTracklib::get_flystick(), DTracklib::get_framenr(), DTracklib::get_glove(), DTracklib::get_marker(), DTracklib::get_meatool(), DTracklib::get_nbody(), DTracklib::get_nbodycal(), DTracklib::get_nflystick(), DTracklib::get_nglove(), DTracklib::get_nmarker(), DTracklib::get_nmeatool(), DTracklib::get_timestamp(), DTrackSDK_Datatypes::DTrack_Hand_Type_f::id, DTrackSDK_Datatypes::DTrack_Marker_Type_f::id, dtracklib_meatool_type::id, dtracklib_flystick_type::id, DTrackSDK_Datatypes::DTrack_Hand_Type_f::lengthphalanx, DTrackSDK_Datatypes::DTrack_Hand_Type_f::loc, DTrackSDK_Datatypes::DTrack_Marker_Type_f::loc, dtracklib_meatool_type::loc, dtracklib_flystick_type::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_f::lr, DTrackSDK_Datatypes::DTrack_Hand_Type_f::nfinger, DTrackSDK_Datatypes::DTrack_Hand_Type_f::quality, DTrackSDK_Datatypes::DTrack_Marker_Type_f::quality, dtracklib_meatool_type::quality, dtracklib_flystick_type::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_f::radiustip, DTrackSDK_Datatypes::DTrack_Hand_Type_f::rot, dtracklib_meatool_type::rot, and dtracklib_flystick_type::rot.
Variable Documentation
DTracklib* dt = NULL [static]
Definition at line 39 of file example_without_remote_control.cpp.