Doxygen: ship_it/DTrackSDK_v2.1.0/Compatibility/DTrack/example_with_remote_control.cpp File Reference
example_with_remote_control.cpp File Reference
#include "DTrack.hpp"
#include <iostream>
#include <sstream>
Functions
static void output_to_console ()
Prints current tracking data to console.
static bool error_to_console ()
Prints error messages to console.
int main (int argc, char **argv)
Main.
Variables
static DTrack * dt = NULL
Function Documentation
static bool error_to_console () [static]
Prints error messages to console.
Returns:
No error occured?
Definition at line 168 of file example_with_remote_control.cpp.
References DTrack::parseerror(), DTrack::timeout(), and DTrack::udperror().
int main (int argc, char ** argv)
Main.
Definition at line 192 of file example_with_remote_control.cpp.
References DTrack::cmd_cameras(), DTrack::cmd_sending_data(), DTrack::cmd_tracking(), error_to_console(), output_to_console(), DTrack::receive(), and DTrack::valid().
static void output_to_console () [static]
Prints current tracking data to console.
Definition at line 44 of file example_with_remote_control.cpp.
References DTrackSDK_Datatypes::DTrack_Hand_Type_f::anglephalanx, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::button, DTrackSDK_Datatypes::DTrack_Hand_Type_f::finger, DTrack::get_body(), DTrack::get_flystick(), DTrack::get_framecounter(), DTrack::get_hand(), DTrack::get_marker(), DTrack::get_meatool(), DTrack::get_num_body(), DTrack::get_num_flystick(), DTrack::get_num_hand(), DTrack::get_num_marker(), DTrack::get_num_meatool(), DTrack::get_timestamp(), DTrackSDK_Datatypes::DTrack_Hand_Type_f::id, DTrackSDK_Datatypes::DTrack_Marker_Type_f::id, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::id, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::id, DTrackSDK_Datatypes::DTrack_Body_Type_f::id, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::joystick, DTrackSDK_Datatypes::DTrack_Hand_Type_f::lengthphalanx, DTrackSDK_Datatypes::DTrack_Hand_Type_f::loc, DTrackSDK_Datatypes::DTrack_Marker_Type_f::loc, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::loc, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::loc, DTrackSDK_Datatypes::DTrack_Body_Type_f::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_f::lr, DTrackSDK_Datatypes::DTrack_Hand_Type_f::nfinger, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::num_button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::num_button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::num_joystick, DTrackSDK_Datatypes::DTrack_Hand_Type_f::quality, DTrackSDK_Datatypes::DTrack_Marker_Type_f::quality, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::quality, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::quality, DTrackSDK_Datatypes::DTrack_Body_Type_f::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_f::radiustip, DTrackSDK_Datatypes::DTrack_Hand_Type_f::rot, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::rot, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::rot, and DTrackSDK_Datatypes::DTrack_Body_Type_f::rot.
Variable Documentation
DTrack* dt = NULL [static]
Definition at line 38 of file example_with_remote_control.cpp.