Doxygen: DTracklib Class Reference
DTracklib Class Reference
Wrapper class for DTrackLib SDK.
#include <DTracklib.hpp>
Public Member Functions
DTracklib (unsigned short udpport=5000, char *remote_ip=NULL, unsigned short remote_port=0, int udpbufsize=10000, unsigned long udptimeout_us=1000000)
Constructor.
~DTracklib (void)
Destructor.
bool valid (void)
Check if initialization was successfull.
bool timeout ()
Check last receive/send error (timeout).
bool udperror ()
Check last receive/send error (udp error).
bool parseerror ()
Check last receive/send error (parser).
bool receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
unsigned long get_framenr ()
Get frame counter.
double get_timestamp ()
Get timestamp.
int get_nbodycal ()
Get number of calibrated bodies.
int get_nbody ()
Get number of standard bodies.
dtracklib_body_type get_body (int id)
Get 6d data.
int get_nflystick ()
Get number of flysticks.
dtracklib_flystick_type get_flystick (int id)
Get 6df data.
int get_nmeatool ()
Get number of measurement tools.
dtracklib_meatool_type get_meatool (int id)
Get 6dmt data.
int get_nglove ()
Get number of fingertracking hands.
dtracklib_glove_type get_glove (int id)
Get gl data.
int get_nmarker ()
Get number of single markers.
dtracklib_marker_type get_marker (int index)
Get 3d data.
bool send (unsigned short cmd, int val=0)
Send one remote control command (UDP; ASCII protocol) to DTrack.
DTracklib (unsigned short udpport=5000, char *remote_ip=NULL, unsigned short remote_port=0, int udpbufsize=10000, unsigned long udptimeout_us=1000000)
Constructor.
~DTracklib (void)
Destructor.
bool valid (void)
Check if initialization was successfull.
bool timeout ()
Check last receive/send error (timeout).
bool udperror ()
Check last receive/send error (udp error).
bool parseerror ()
Check last receive/send error (parser).
bool receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
unsigned long get_framenr ()
Get frame counter.
double get_timestamp ()
Get timestamp.
int get_nbodycal ()
Get number of calibrated bodies.
int get_nbody ()
Get number of standard bodies.
dtracklib_body_type get_body (int id)
Get 6d data.
int get_nflystick ()
Get number of flysticks.
dtracklib_flystick_type get_flystick (int id)
Get 6df data.
int get_nmeatool ()
Get number of measurement tools.
dtracklib_meatool_type get_meatool (int id)
Get 6dmt data.
int get_nglove ()
Get number of fingertracking hands.
dtracklib_glove_type get_glove (int id)
Get gl data.
int get_nmarker ()
Get number of single markers.
dtracklib_marker_type get_marker (int index)
Get 3d data.
bool send (unsigned short cmd, int val=0)
Send one remote control command (UDP; ASCII protocol) to DTrack.
DTracklib (unsigned short udpport=5000, char *remote_ip=NULL, unsigned short remote_port=0, int udpbufsize=10000, unsigned long udptimeout_us=1000000)
Constructor.
~DTracklib (void)
Destructor.
bool valid (void)
Check if initialization was successfull.
bool timeout ()
Check last receive/send error (timeout).
bool udperror ()
Check last receive/send error (udp error).
bool parseerror ()
Check last receive/send error (parser).
bool receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
unsigned long get_framenr ()
Get frame counter.
double get_timestamp ()
Get timestamp.
int get_nbodycal ()
Get number of calibrated bodies.
int get_nbody ()
Get number of standard bodies.
dtracklib_body_type get_body (int id)
Get 6d data.
int get_nflystick ()
Get number of flysticks.
dtracklib_flystick_type get_flystick (int id)
Get 6df data.
int get_nmeatool ()
Get number of measurement tools.
dtracklib_meatool_type get_meatool (int id)
Get 6dmt data.
int get_nglove ()
Get number of fingertracking hands.
dtracklib_glove_type get_glove (int id)
Get gl data.
int get_nmarker ()
Get number of single markers.
dtracklib_marker_type get_marker (int index)
Get 3d data.
bool send (unsigned short cmd, int val=0)
Send one remote control command (UDP; ASCII protocol) to DTrack.
Detailed Description
Wrapper class for DTrackLib SDK.
Definition at line 74 of file DTracklib.hpp.
Constructor & Destructor Documentation
DTracklib::DTracklib (unsigned short udpport = 5000, char * remote_ip = NULL, unsigned short remote_port = 0, int udpbufsize = 10000, unsigned long udptimeout_us = 1000000)
Constructor.
Parameters:
[in] udpport UDP port number to receive data from DTrack
[in] remote_ip DTrack remote control: ip address of DTrack PC (NULL if not used)
[in] remote_port port number of DTrack remote control (0 if not used)
[in] udpbufsize size of buffer for UDP packets (in bytes)
[in] udptimeout_us UDP timeout (receiving and sending) in us (micro sec)
Definition at line 50 of file DTracklib.cpp.
References DTrackSDK::SYS_DTRACK.
DTracklib::~DTracklib (void)
Destructor.
Definition at line 67 of file DTracklib.cpp.
DTracklib::DTracklib (unsigned short udpport = 5000, char * remote_ip = NULL, unsigned short remote_port = 0, int udpbufsize = 10000, unsigned long udptimeout_us = 1000000)
Constructor.
Parameters:
[in] udpport UDP port number to receive data from DTrack
[in] remote_ip DTrack remote control: ip address of DTrack PC (NULL if not used)
[in] remote_port port number of DTrack remote control (0 if not used)
[in] udpbufsize size of buffer for UDP packets (in bytes)
[in] udptimeout_us UDP timeout (receiving and sending) in us (micro sec)
DTracklib::~DTracklib (void)
Destructor.
DTracklib::DTracklib (unsigned short udpport = 5000, char * remote_ip = NULL, unsigned short remote_port = 0, int udpbufsize = 10000, unsigned long udptimeout_us = 1000000)
Constructor.
Parameters:
[in] udpport UDP port number to receive data from DTrack
[in] remote_ip DTrack remote control: ip address of DTrack PC (NULL if not used)
[in] remote_port port number of DTrack remote control (0 if not used)
[in] udpbufsize size of buffer for UDP packets (in bytes)
[in] udptimeout_us UDP timeout (receiving and sending) in us (micro sec)
DTracklib::~DTracklib (void)
Destructor.
Member Function Documentation
bool DTracklib::valid (void)
Check if initialization was successfull.
Returns:
Valid?
Definition at line 78 of file DTracklib.cpp.
References DTrackSDK::isLocalDataPortValid().
Referenced by main().
bool DTracklib::timeout ()
Check last receive/send error (timeout).
Returns:
timeout occured?
Definition at line 89 of file DTracklib.cpp.
References DTrackSDK::ERR_TIMEOUT, and DTrackSDK::getLastDataError().
Referenced by error_to_console().
bool DTracklib::udperror ()
Check last receive/send error (udp error).
Returns:
udp error occured?
Definition at line 100 of file DTracklib.cpp.
References DTrackSDK::ERR_NET, and DTrackSDK::getLastDataError().
Referenced by error_to_console().
bool DTracklib::parseerror ()
Check last receive/send error (parser).
Returns:
error occured while parsing tracking data?
Definition at line 111 of file DTracklib.cpp.
References DTrackSDK::ERR_PARSE, and DTrackSDK::getLastDataError().
Referenced by error_to_console().
bool DTracklib::receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
Returns:
successful?
Definition at line 122 of file DTracklib.cpp.
References dtracklib_flystick_type::ang, dtracklib_body_type::ang, DTrackSDK_Datatypes::DTrack_Hand_Type_d::anglephalanx, DTrackSDK_Datatypes::DTrack_Hand_Type_f::anglephalanx, dtracklib_meatool_type::bt, dtracklib_flystick_type::bt, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::button, DTRACK_FLYSTICK_MAX_BUTTON, DTRACK_HAND_MAX_FINGER, DTrackSDK_Datatypes::DTrack_Hand_Type_d::finger, DTrackSDK_Datatypes::DTrack_Hand_Type_f::finger, DTrackSDK::getBody(), DTrackSDK::getFlyStick(), DTrackSDK::getHand(), DTrackSDK::getMarker(), DTrackSDK::getMeaTool(), DTrackSDK::getNumBody(), DTrackSDK::getNumFlyStick(), DTrackSDK::getNumHand(), DTrackSDK::getNumMarker(), DTrackSDK::getNumMeaTool(), DTrackSDK_Datatypes::DTrack_Marker_Type_d::id, DTrackSDK_Datatypes::DTrack_Marker_Type_f::id, DTrackSDK_Datatypes::DTrack_Hand_Type_d::id, DTrackSDK_Datatypes::DTrack_Hand_Type_f::id, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::id, dtracklib_meatool_type::id, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::id, dtracklib_flystick_type::id, DTrackSDK_Datatypes::DTrack_Body_Type_d::id, dtracklib_body_type::id, DTrackSDK_Datatypes::DTrack_Hand_Type_d::lengthphalanx, DTrackSDK_Datatypes::DTrack_Hand_Type_f::lengthphalanx, DTrackSDK_Datatypes::DTrack_Marker_Type_d::loc, DTrackSDK_Datatypes::DTrack_Marker_Type_f::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_d::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_f::loc, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::loc, dtracklib_meatool_type::loc, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::loc, dtracklib_flystick_type::loc, DTrackSDK_Datatypes::DTrack_Body_Type_d::loc, dtracklib_body_type::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_d::lr, DTrackSDK_Datatypes::DTrack_Hand_Type_f::lr, DTrackSDK_Datatypes::DTrack_Hand_Type_d::nfinger, DTrackSDK_Datatypes::DTrack_Hand_Type_f::nfinger, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::num_button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::num_button, DTrackSDK_Datatypes::DTrack_Marker_Type_d::quality, DTrackSDK_Datatypes::DTrack_Marker_Type_f::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_d::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_f::quality, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::quality, dtracklib_meatool_type::quality, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::quality, dtracklib_flystick_type::quality, DTrackSDK_Datatypes::DTrack_Body_Type_d::quality, dtracklib_body_type::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_d::radiustip, DTrackSDK_Datatypes::DTrack_Hand_Type_f::radiustip, DTrackSDK::receive(), DTrackSDK_Datatypes::DTrack_Hand_Type_d::rot, DTrackSDK_Datatypes::DTrack_Hand_Type_f::rot, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::rot, dtracklib_meatool_type::rot, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::rot, dtracklib_flystick_type::rot, DTrackSDK_Datatypes::DTrack_Body_Type_d::rot, and dtracklib_body_type::rot.
Referenced by main().
unsigned long DTracklib::get_framenr ()
Get frame counter.
Refers to last received frame.
Returns:
frame counter
Definition at line 234 of file DTracklib.cpp.
References DTrackSDK::getFrameCounter().
Referenced by output_to_console().
double DTracklib::get_timestamp ()
Get timestamp.
Refers to last received frame.
Returns:
timestamp (-1 if information not available)
Definition at line 246 of file DTracklib.cpp.
References DTrackSDK::getTimeStamp().
Referenced by output_to_console().
int DTracklib::get_nbodycal ()
Get number of calibrated bodies.
Returns:
number of calibrated bodies; -1, if information not available
Definition at line 257 of file DTracklib.cpp.
Referenced by output_to_console().
int DTracklib::get_nbody ()
Get number of standard bodies.
Refers to last received frame.
Returns:
number of standard bodies
Definition at line 269 of file DTracklib.cpp.
Referenced by output_to_console().
dtracklib_body_type DTracklib::get_body (int id)
Get 6d data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. nbody - 1
Returns:
id-th standard body data.
Definition at line 282 of file DTracklib.cpp.
Referenced by output_to_console().
int DTracklib::get_nflystick ()
Get number of flysticks.
Refers to last received frame.
Returns:
number of flysticks
Definition at line 300 of file DTracklib.cpp.
Referenced by output_to_console().
dtracklib_flystick_type DTracklib::get_flystick (int id)
Get 6df data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. nflystick - 1
Returns:
id-th flystick data
Definition at line 313 of file DTracklib.cpp.
Referenced by output_to_console().
int DTracklib::get_nmeatool ()
Get number of measurement tools.
Refers to last received frame.
Returns:
number of measurement tools
Definition at line 331 of file DTracklib.cpp.
Referenced by output_to_console().
dtracklib_meatool_type DTracklib::get_meatool (int id)
Get 6dmt data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. nmeatool - 1
Returns:
id-th measurement tool data
Definition at line 344 of file DTracklib.cpp.
Referenced by output_to_console().
int DTracklib::get_nglove ()
Get number of fingertracking hands.
Refers to last received frame.
Returns:
number of fingertracking hands
Definition at line 362 of file DTracklib.cpp.
Referenced by output_to_console().
dtracklib_glove_type DTracklib::get_glove (int id)
Get gl data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. nglove - 1
Returns:
id-th Fingertracking hand data.
Definition at line 375 of file DTracklib.cpp.
Referenced by output_to_console().
int DTracklib::get_nmarker ()
Get number of single markers.
Refers to last received frame.
Returns:
number of single markers
Definition at line 393 of file DTracklib.cpp.
Referenced by output_to_console().
dtracklib_marker_type DTracklib::get_marker (int index)
Get 3d data.
Refers to last received frame.
Parameters:
[in] index index, range 0 .. nmarker - 1
Returns:
i-th single marker data
Definition at line 406 of file DTracklib.cpp.
Referenced by output_to_console().
bool DTracklib::send (unsigned short cmd, int val = 0)
Send one remote control command (UDP; ASCII protocol) to DTrack.
Parameters:
[in] cmd command code
[in] val additional value (depends on command code), default 0
Returns:
sending was successful
Definition at line 425 of file DTracklib.cpp.
References DTRACKLIB_CMD_CAMERAS_AND_CALC_ON, DTRACKLIB_CMD_CAMERAS_OFF, DTRACKLIB_CMD_CAMERAS_ON, DTRACKLIB_CMD_SEND_DATA, DTRACKLIB_CMD_SEND_N_DATA, DTRACKLIB_CMD_STOP_DATA, DTrackSDK::isLocalDataPortValid(), and DTrackSDK::sendCommand().
Referenced by main().
bool DTracklib::valid (void)
Check if initialization was successfull.
Returns:
Valid?
bool DTracklib::timeout ()
Check last receive/send error (timeout).
Returns:
timeout occured?
bool DTracklib::udperror ()
Check last receive/send error (udp error).
Returns:
udp error occured?
bool DTracklib::parseerror ()
Check last receive/send error (parser).
Returns:
error occured while parsing tracking data?
bool DTracklib::receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
Returns:
successful?
unsigned long DTracklib::get_framenr ()
Get frame counter.
Refers to last received frame.
Returns:
frame counter
double DTracklib::get_timestamp ()
Get timestamp.
Refers to last received frame.
Returns:
timestamp (-1 if information not available)
int DTracklib::get_nbodycal ()
Get number of calibrated bodies.
Returns:
number of calibrated bodies; -1, if information not available
int DTracklib::get_nbody ()
Get number of standard bodies.
Refers to last received frame.
Returns:
number of standard bodies
dtracklib_body_type DTracklib::get_body (int id)
Get 6d data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. nbody - 1
Returns:
id-th standard body data.
int DTracklib::get_nflystick ()
Get number of flysticks.
Refers to last received frame.
Returns:
number of flysticks
dtracklib_flystick_type DTracklib::get_flystick (int id)
Get 6df data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. nflystick - 1
Returns:
id-th flystick data
int DTracklib::get_nmeatool ()
Get number of measurement tools.
Refers to last received frame.
Returns:
number of measurement tools
dtracklib_meatool_type DTracklib::get_meatool (int id)
Get 6dmt data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. nmeatool - 1
Returns:
id-th measurement tool data
int DTracklib::get_nglove ()
Get number of fingertracking hands.
Refers to last received frame.
Returns:
number of fingertracking hands
dtracklib_glove_type DTracklib::get_glove (int id)
Get gl data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. nglove - 1
Returns:
id-th Fingertracking hand data.
int DTracklib::get_nmarker ()
Get number of single markers.
Refers to last received frame.
Returns:
number of single markers
dtracklib_marker_type DTracklib::get_marker (int index)
Get 3d data.
Refers to last received frame.
Parameters:
[in] index index, range 0 .. nmarker - 1
Returns:
i-th single marker data
bool DTracklib::send (unsigned short cmd, int val = 0)
Send one remote control command (UDP; ASCII protocol) to DTrack.
Parameters:
[in] cmd command code
[in] val additional value (depends on command code), default 0
Returns:
sending was successful
bool DTracklib::valid (void)
Check if initialization was successfull.
Returns:
Valid?
bool DTracklib::timeout ()
Check last receive/send error (timeout).
Returns:
timeout occured?
bool DTracklib::udperror ()
Check last receive/send error (udp error).
Returns:
udp error occured?
bool DTracklib::parseerror ()
Check last receive/send error (parser).
Returns:
error occured while parsing tracking data?
bool DTracklib::receive ()
Receive and process one DTrack data packet (UDP; ASCII protocol).
Returns:
successful?
unsigned long DTracklib::get_framenr ()
Get frame counter.
Refers to last received frame.
Returns:
frame counter
double DTracklib::get_timestamp ()
Get timestamp.
Refers to last received frame.
Returns:
timestamp (-1 if information not available)
int DTracklib::get_nbodycal ()
Get number of calibrated bodies.
Returns:
number of calibrated bodies; -1, if information not available
int DTracklib::get_nbody ()
Get number of standard bodies.
Refers to last received frame.
Returns:
number of standard bodies
dtracklib_body_type DTracklib::get_body (int id)
Get 6d data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. nbody - 1
Returns:
id-th standard body data.
int DTracklib::get_nflystick ()
Get number of flysticks.
Refers to last received frame.
Returns:
number of flysticks
dtracklib_flystick_type DTracklib::get_flystick (int id)
Get 6df data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. nflystick - 1
Returns:
id-th flystick data
int DTracklib::get_nmeatool ()
Get number of measurement tools.
Refers to last received frame.
Returns:
number of measurement tools
dtracklib_meatool_type DTracklib::get_meatool (int id)
Get 6dmt data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. nmeatool - 1
Returns:
id-th measurement tool data
int DTracklib::get_nglove ()
Get number of fingertracking hands.
Refers to last received frame.
Returns:
number of fingertracking hands
dtracklib_glove_type DTracklib::get_glove (int id)
Get gl data.
Refers to last received frame.
Parameters:
[in] id id, range 0 .. nglove - 1
Returns:
id-th Fingertracking hand data.
int DTracklib::get_nmarker ()
Get number of single markers.
Refers to last received frame.
Returns:
number of single markers
dtracklib_marker_type DTracklib::get_marker (int index)
Get 3d data.
Refers to last received frame.
Parameters:
[in] index index, range 0 .. nmarker - 1
Returns:
i-th single marker data
bool DTracklib::send (unsigned short cmd, int val = 0)
Send one remote control command (UDP; ASCII protocol) to DTrack.
Parameters:
[in] cmd command code
[in] val additional value (depends on command code), default 0
Returns:
sending was successful
The documentation for this class was generated from the following files:
Compatibility/DTrackLib/DTracklib.hpp
ship_it/DTrackSDK_v2.1.0/Compatibility/DTrackLib/DTracklib.hpp
ship_it/DTrackSDK_v2.2.0/Compatibility/DTrackLib/DTracklib.hpp
Compatibility/DTrackLib/DTracklib.cpp
ship_it/DTrackSDK_v2.1.0/Compatibility/DTrackLib/DTracklib.cpp
ship_it/DTrackSDK_v2.2.0/Compatibility/DTrackLib/DTracklib.cpp