Doxygen: DTrackSDK_Net Namespace Reference
DTrackSDK_Net Namespace Reference
Functions
void net_init (void)
Initialize network ressources.
void net_exit (void)
Free network ressources.
unsigned int ip_name2ip (const char *name)
Convert string to IP address.
int udp_init (void **sock, unsigned short *port, unsigned int ip)
Initialize UDP socket.
int udp_exit (void *sock, unsigned int ip)
Deinitialize UDP socket.
int udp_receive (const void *sock, void *buffer, int maxlen, int tout_us)
Receive UDP data.
int udp_send (const void *sock, void *buffer, int len, unsigned int ipaddr, unsigned short port, int tout_us)
Send UDP data.
int tcp_client_init (void **sock, unsigned int ip, unsigned short port)
Initialize client TCP socket.
int tcp_exit (void *sock)
Deinitialize TCP socket.
int tcp_receive (const void *sock, void *buffer, int maxlen, int tout_us)
Receive TCP data.
int tcp_send (const void *sock, const void *buffer, int len, int tout_us)
Send TCP data.
Function Documentation
unsigned int DTrackSDK_Net::ip_name2ip (const char * name)
Convert string to IP address.
Parameters:
[in] name IPv4 dotted decimal address or hostname
Returns:
IP address, 0 if error occured
Definition at line 77 of file DTrackNet.cpp.
void DTrackSDK_Net::net_exit (void)
Free network ressources.
Definition at line 63 of file DTrackNet.cpp.
Referenced by DTrackSDK::~DTrackSDK().
void DTrackSDK_Net::net_init (void)
Initialize network ressources.
Definition at line 45 of file DTrackNet.cpp.
int DTrackSDK_Net::tcp_client_init (void ** sock, unsigned int ip, unsigned short port)
Initialize client TCP socket.
Parameters:
[out] sock socket number
[in] ip ip address of TCP server
[in] port port number of TCP server
Returns:
0 if ok, <0 if error occured
Definition at line 348 of file DTrackNet.cpp.
References tcp_exit().
int DTrackSDK_Net::tcp_exit (void * sock)
Deinitialize TCP socket.
Parameters:
[in] sock socket number
Returns:
0 ok, -1 error
Definition at line 408 of file DTrackNet.cpp.
References _ip_socket_struct::ossock.
Referenced by DTrackSDK::sendDTrack2Command(), tcp_client_init(), and DTrackSDK::~DTrackSDK().
int DTrackSDK_Net::tcp_receive (const void * sock, void * buffer, int maxlen, int tout_us)
Receive TCP data.
Parameters:
[in] sock socket number
[out] buffer buffer for TCP data
[in] maxlen length of buffer
[in] tout_us timeout in us (micro sec)
Returns:
number of received bytes, <0 if error/timeout occured, -9 broken connection
Definition at line 441 of file DTrackNet.cpp.
References _ip_socket_struct::ossock.
Referenced by DTrackSDK::sendDTrack2Command().
int DTrackSDK_Net::tcp_send (const void * sock, const void * buffer, int len, int tout_us)
Send TCP data.
Parameters:
[in] sock socket number
[in] buffer buffer for TCP data
[in] len length of buffer
[in] tout_us timeout in us (micro sec)
Returns:
0 if ok, <0 if error/timeout occured
Definition at line 488 of file DTrackNet.cpp.
References _ip_socket_struct::ossock.
Referenced by DTrackSDK::sendDTrack2Command().
int DTrackSDK_Net::udp_exit (void * sock, unsigned int ip)
Deinitialize UDP socket.
Parameters:
[in] sock socket number
[in] ip multicast ip to drop
Returns:
0 ok, -1 error
Definition at line 198 of file DTrackNet.cpp.
References _ip_socket_struct::ossock.
Referenced by udp_init(), and DTrackSDK::~DTrackSDK().
int DTrackSDK_Net::udp_init (void ** sock, unsigned short * port, unsigned int ip)
Initialize UDP socket.
Parameters:
[out] sock socket number
[in,out] port port number, 0 if to be chosen by the OS
[in] ip multicast ip to listen
Returns:
0 if ok, < 0 if error occured
Definition at line 108 of file DTrackNet.cpp.
References _ip_socket_struct::ossock, and udp_exit().
int DTrackSDK_Net::udp_receive (const void * sock, void * buffer, int maxlen, int tout_us)
Receive UDP data.
Tries to receive one packet, as long as data is available.
Parameters:
[in] sock socket number
[out] buffer buffer for UDP data
[in] maxlen length of buffer
[in] tout_us timeout in us (micro sec)
Returns:
number of received bytes, <0 if error/timeout occured
Definition at line 243 of file DTrackNet.cpp.
References _ip_socket_struct::ossock.
Referenced by DTrackSDK::receive().
int DTrackSDK_Net::udp_send (const void * sock, void * buffer, int len, unsigned int ipaddr, unsigned short port, int tout_us)
Send UDP data.
Parameters:
[in] sock socket number
[in] buffer buffer for UDP data
[in] len length of buffer
[in] ipaddr IPv4 address to send data to
[in] port port number to send data to
[in] tout_us timeout in us (micro sec)
Returns:
0 if ok, <0 if error/timeout occured
Definition at line 301 of file DTrackNet.cpp.
References _ip_socket_struct::ossock.
Referenced by DTrackSDK::sendCommand().