Doxygen: DTrackSDK_Parse Namespace Reference
DTrackSDK_Parse Namespace Reference
Functions
char * string_nextline (char *str, char *start, int len)
Search next line in buffer.
char * string_get_i (char *str, int *i)
Read next 'int' value from string.
char * string_get_ui (char *str, unsigned int *ui)
Read next 'unsigned int' value from string.
char * string_get_d (char *str, double *d)
Read next 'double' value from string.
char * string_get_f (char *str, float *f)
Read next 'float' value from string.
char * string_get_block (char *str, const char *fmt, int *idat, float *fdat, double *ddat)
Process next block '[.
char * string_get_word (char *str, std::string &w)
Read next 'word' value from string.
char * string_get_quoted_text (char *str, std::string &qt)
Read next 'quoted text' value from string.
char * string_cmp_parameter (char *str, const char *p)
Compare strings regarding DTrack2 parameter rules.
Function Documentation
char * DTrackSDK_Parse::string_cmp_parameter (char * str, const char * p)
Compare strings regarding DTrack2 parameter rules.
Parameters:
str string
p parameter string
Returns:
pointer behind parameter in str; NULL in case of error
Definition at line 239 of file DTrackParse.cpp.
Referenced by DTrackSDK::getParam().
char * DTrackSDK_Parse::string_get_block (char * str, const char * fmt, int * idat, float * fdat, double * ddat)
Process next block '[.
..]' in string
Parameters:
[in] str string
[in] fmt format string ('i' for 'int', 'f' for 'float')
[out] idat array for 'int' values (long enough due to fmt)
[out] fdat array for 'float' values (long enough due to fmt)
[out] ddat array for 'double' values (long enough due to fmt)
Returns:
pointer behind read value in str; NULL in case of error
Definition at line 128 of file DTrackParse.cpp.
References string_get_d(), string_get_f(), and string_get_i().
Referenced by DTrackSDK::receive().
char * DTrackSDK_Parse::string_get_d (char * str, double * d)
Read next 'double' value from string.
Parameters:
[in] str string
[out] d read value
Returns:
pointer behind read value in str; NULL in case of error
Definition at line 95 of file DTrackParse.cpp.
Referenced by DTrackSDK::receive(), and string_get_block().
char * DTrackSDK_Parse::string_get_f (char * str, float * f)
Read next 'float' value from string.
Parameters:
[in] str string
[out] f read value
Returns:
pointer behind read value in str; NULL in case of error
Definition at line 110 of file DTrackParse.cpp.
Referenced by string_get_block().
char * DTrackSDK_Parse::string_get_i (char * str, int * i)
Read next 'int' value from string.
Parameters:
[in] str string
[out] i read value
Returns:
pointer behind read value in str; NULL in case of error
Definition at line 65 of file DTrackParse.cpp.
Referenced by DTrackSDK::receive(), DTrackSDK::sendDTrack2Command(), and string_get_block().
char * DTrackSDK_Parse::string_get_quoted_text (char * str, std::string & qt)
Read next 'quoted text' value from string.
Parameters:
[in] str string
[out] qt read value (without quotes)
Returns:
pointer behind read value in str; NULL in case of error
Parameters:
[in] str string
[out] qt read value (without quotes)
Returns:
pointer behind read value in str; NULL in case of error
Definition at line 215 of file DTrackParse.cpp.
Referenced by DTrackSDK::getMessage(), and DTrackSDK::sendDTrack2Command().
char * DTrackSDK_Parse::string_get_ui (char * str, unsigned int * ui)
Read next 'unsigned int' value from string.
Parameters:
[in] str string
[out] ui read value
Returns:
pointer behind read value in str; NULL in case of error
Definition at line 80 of file DTrackParse.cpp.
Referenced by DTrackSDK::getMessage(), and DTrackSDK::receive().
char * DTrackSDK_Parse::string_get_word (char * str, std::string & w)
Read next 'word' value from string.
Parameters:
[in] str string
[out] w read value
Returns:
pointer behind read value in str; NULL in case of error
Parameters:
[in] str string
[out] w read value
Returns:
pointer behind read value in str; NULL in case of error
Definition at line 186 of file DTrackParse.cpp.
Referenced by DTrackSDK::getMessage().
char * DTrackSDK_Parse::string_nextline (char * str, char * start, int len)
Search next line in buffer.
Parameters:
[in] str buffer (total)
[in] start start position within buffer
[in] len buffer length in bytes
Returns:
begin of line, NULL if no new line in buffer
Definition at line 36 of file DTrackParse.cpp.
Referenced by DTrackSDK::receive().