Doxygen: ship_it/DTrackSDK_v2.1.0/example_with_dtrack2_remote_control.cpp File Reference
example_with_dtrack2_remote_control.cpp File Reference
#include "DTrackSDK.hpp"
#include <iostream>
#include <sstream>
Functions
static void output_to_console ()
Prints current tracking data to console.
static bool data_error_to_console ()
Prints error messages to console.
static void messages_to_console ()
Prints ATC messages to console.
int main (int argc, char **argv)
Main.
Variables
static DTrackSDK * dt = NULL
Function Documentation
static bool data_error_to_console () [static]
Prints error messages to console.
Returns:
No error occured?
Definition at line 194 of file example_with_dtrack2_remote_control.cpp.
References DTrackSDK::ERR_NET, DTrackSDK::ERR_PARSE, DTrackSDK::ERR_TIMEOUT, and DTrackSDK::getLastDataError().
int main (int argc, char ** argv)
Main.
Definition at line 229 of file example_with_dtrack2_remote_control.cpp.
References data_error_to_console(), DTrackSDK::getDataPort(), DTrackSDK::isCommandInterfaceValid(), DTrackSDK::isLocalDataPortValid(), messages_to_console(), output_to_console(), DTrackSDK::receive(), DTrackSDK::startMeasurement(), and DTrackSDK::stopMeasurement().
static void messages_to_console () [static]
Prints ATC messages to console.
Definition at line 218 of file example_with_dtrack2_remote_control.cpp.
References DTrackSDK::getMessage(), DTrackSDK::getMessageMsg(), and DTrackSDK::getMessageStatus().
static void output_to_console () [static]
Prints current tracking data to console.
Definition at line 44 of file example_with_dtrack2_remote_control.cpp.
References DTrackSDK_Datatypes::DTrack_Human_Type_d::ang, DTrackSDK_Datatypes::DTrack_Hand_Type_d::anglephalanx, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::button, DTrackSDK_Datatypes::DTrack_Hand_Type_d::finger, DTrackSDK::getBody(), DTrackSDK::getFlyStick(), DTrackSDK::getFrameCounter(), DTrackSDK::getHand(), DTrackSDK::getHuman(), DTrackSDK::getMarker(), DTrackSDK::getMeaTool(), DTrackSDK::getNumBody(), DTrackSDK::getNumFlyStick(), DTrackSDK::getNumHand(), DTrackSDK::getNumHuman(), DTrackSDK::getNumMarker(), DTrackSDK::getNumMeaTool(), DTrackSDK::getTimeStamp(), DTrackSDK_Datatypes::DTrack_Human_Type_d::id, DTrackSDK_Datatypes::DTrack_Hand_Type_d::id, DTrackSDK_Datatypes::DTrack_Marker_Type_d::id, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::id, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::id, DTrackSDK_Datatypes::DTrack_Body_Type_d::id, DTrackSDK_Datatypes::DTrack_Human_Type_d::joint, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::joystick, DTrackSDK_Datatypes::DTrack_Hand_Type_d::lengthphalanx, DTrackSDK_Datatypes::DTrack_Human_Type_d::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_d::loc, DTrackSDK_Datatypes::DTrack_Marker_Type_d::loc, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::loc, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::loc, DTrackSDK_Datatypes::DTrack_Body_Type_d::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_d::lr, DTrackSDK_Datatypes::DTrack_Hand_Type_d::nfinger, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::num_button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::num_button, DTrackSDK_Datatypes::DTrack_Human_Type_d::num_joints, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::num_joystick, DTrackSDK_Datatypes::DTrack_Human_Type_d::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_d::quality, DTrackSDK_Datatypes::DTrack_Marker_Type_d::quality, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::quality, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::quality, DTrackSDK_Datatypes::DTrack_Body_Type_d::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_d::radiustip, DTrackSDK_Datatypes::DTrack_Human_Type_d::rot, DTrackSDK_Datatypes::DTrack_Hand_Type_d::rot, DTrackSDK_Datatypes::DTrack_MeaTool_Type_d::rot, DTrackSDK_Datatypes::DTrack_FlyStick_Type_d::rot, and DTrackSDK_Datatypes::DTrack_Body_Type_d::rot.
Variable Documentation
DTrackSDK* dt = NULL [static]
Definition at line 38 of file example_with_dtrack2_remote_control.cpp.