Doxygen: ship_it/DTrackSDK_v2.1.0/Compatibility/DTrack2/example_without_remote_control.cpp File Reference
example_without_remote_control.cpp File Reference
#include "DTrack2.hpp"
#include <iostream>
#include <sstream>
Functions
static void output_to_console ()
Prints current tracking data to console.
static bool error_to_console ()
Prints error messages to console.
int main (int argc, char **argv)
Main.
Variables
static DTrack2 * dt = NULL
Function Documentation
static bool error_to_console () [static]
Prints error messages to console.
Returns:
No error occured?
Definition at line 167 of file example_without_remote_control.cpp.
References DTrack2::data_neterror(), DTrack2::data_parseerror(), and DTrack2::data_timeout().
int main (int argc, char ** argv)
Main.
Definition at line 191 of file example_without_remote_control.cpp.
References error_to_console(), output_to_console(), DTrack2::receive(), and DTrack2::valid().
static void output_to_console () [static]
Prints current tracking data to console.
Definition at line 43 of file example_without_remote_control.cpp.
References DTrackSDK_Datatypes::DTrack_Hand_Type_f::anglephalanx, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::button, DTrackSDK_Datatypes::DTrack_Hand_Type_f::finger, DTrack2::get_body(), DTrack2::get_flystick(), DTrack2::get_framecounter(), DTrack2::get_hand(), DTrack2::get_marker(), DTrack2::get_meatool(), DTrack2::get_num_body(), DTrack2::get_num_flystick(), DTrack2::get_num_hand(), DTrack2::get_num_marker(), DTrack2::get_num_meatool(), DTrack2::get_timestamp(), DTrackSDK_Datatypes::DTrack_Hand_Type_f::id, DTrackSDK_Datatypes::DTrack_Marker_Type_f::id, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::id, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::id, DTrackSDK_Datatypes::DTrack_Body_Type_f::id, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::joystick, DTrackSDK_Datatypes::DTrack_Hand_Type_f::lengthphalanx, DTrackSDK_Datatypes::DTrack_Hand_Type_f::loc, DTrackSDK_Datatypes::DTrack_Marker_Type_f::loc, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::loc, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::loc, DTrackSDK_Datatypes::DTrack_Body_Type_f::loc, DTrackSDK_Datatypes::DTrack_Hand_Type_f::lr, DTrackSDK_Datatypes::DTrack_Hand_Type_f::nfinger, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::num_button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::num_button, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::num_joystick, DTrackSDK_Datatypes::DTrack_Hand_Type_f::quality, DTrackSDK_Datatypes::DTrack_Marker_Type_f::quality, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::quality, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::quality, DTrackSDK_Datatypes::DTrack_Body_Type_f::quality, DTrackSDK_Datatypes::DTrack_Hand_Type_f::radiustip, DTrackSDK_Datatypes::DTrack_Hand_Type_f::rot, DTrackSDK_Datatypes::DTrack_MeaTool_Type_f::rot, DTrackSDK_Datatypes::DTrack_FlyStick_Type_f::rot, and DTrackSDK_Datatypes::DTrack_Body_Type_f::rot.
Variable Documentation
DTrack2* dt = NULL [static]
Definition at line 37 of file example_without_remote_control.cpp.